"""Emit the per-scheme GPU-op savepoint-parity deliverables for YSU + ACM2.

Wraps the EXISTING WRF-oracle savepoint parity reports (regenerated by
``tests/test_v060_pbl_{ysu,acm2}.py`` against the unmodified pristine-WRF module
savepoints) together with the traceable-vs-host transcription cross-check into the
``{ysu,acm2}_gpuop_savepoint_parity.json`` deliverables: an explicit statement that
the GPU-operational (jax.lax.scan-traceable, vmap-batched, scan-wired) kernel is the
one that produced the parity verdict, with NO loosened tolerance.

Run order: parity tests -> pbl_trace_vs_host.py -> THIS.
CPU JAX fp64, cores 0-3.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
V060 = ROOT / "proofs" / "v060"


def _load(name: str) -> dict:
    return json.loads((V060 / name).read_text())


def _emit(scheme: str, entry: str, adapter: str, bl_opt: int, traced_fn: str) -> dict:
    parity = _load(f"{scheme}_savepoint_parity_report.json")
    trace = _load("pbl_trace_vs_host.json")[scheme]
    report = {
        "schema": f"gpuwrf.v060.{scheme}_gpuop_savepoint_parity.v1",
        "scheme": parity["scheme"],
        "bl_pbl_physics": bl_opt,
        "gpu_operational": True,
        "verdict": "PASS"
        if (parity["verdict"] == "PASS" and trace["verdict"] == "PASS")
        else "FAIL",
        "what_this_proves": (
            "The GPU-operational kernel -- the jax.lax.scan-traceable / jax.vmap-"
            f"batched {traced_fn} that the operational scan PBL slot dispatches via "
            f"{adapter} -- reproduces the unmodified-WRF module oracle within the SAME "
            "predeclared fp64 savepoint tolerances as the original host-NumPy lane. The "
            "single-column public entry " + entry + " now calls the traceable kernel, so "
            "the parity report below is the GPU-op verdict directly; the trace-vs-host "
            "cross-check confirms traceable == host-NumPy == WRF to machine precision."
        ),
        "predeclared_tolerances": parity["predeclared_tolerances"],
        "tolerances_loosened_for_gpuop": False,
        "oracle": parity["oracle"],
        "savepoint_parity": {
            "verdict": parity["verdict"],
            "regimes_covered": parity["regimes_covered"],
            "cases_pass": [c["pass"] for c in parity["cases"]],
        },
        "trace_vs_host_numpy": {
            "verdict": trace["verdict"],
            "worst_abs": trace["worst_abs"],
            "cases": [
                {"case": c["case"], "worst_abs": c["worst_abs"],
                 "worst_rel": c["worst_rel"], "kpbl_match": c["kpbl_match"],
                 **({"noconv_match": c["noconv_match"]} if "noconv_match" in c else {}),
                 "pass": c["pass"]}
                for c in trace["cases"]
            ],
            "proof": "proofs/v060/pbl_trace_vs_host.json",
        },
        "scan_wire": {
            "adapter": adapter,
            "operational_slot": "runtime.operational_mode PBL slot "
            "(PBL_SCAN_ADAPTERS dispatch on static bl_pbl_physics)",
            "gpu_op_smoke": "proofs/v060/pbl_gpuop_smoke.json",
        },
        "full_savepoint_parity_report": f"proofs/v060/{scheme}_savepoint_parity_report.json",
    }
    out = V060 / f"{scheme}_gpuop_savepoint_parity.json"
    out.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    return report


def run() -> dict:
    ysu = _emit(
        "ysu", "pbl_ysu.step_ysu_column",
        "coupling.scan_adapters.ysu_pbl_adapter", 1,
        "pbl_ysu._ysu_column_traceable / pbl_ysu.ysu_columns",
    )
    acm2 = _emit(
        "acm2", "pbl_acm2.step_acm2_column",
        "coupling.scan_adapters.acm2_pbl_adapter", 7,
        "pbl_acm2._acm2_column_traceable / pbl_acm2.acm2_columns",
    )
    return {
        "ysu_verdict": ysu["verdict"],
        "ysu_trace_worst_abs": ysu["trace_vs_host_numpy"]["worst_abs"],
        "acm2_verdict": acm2["verdict"],
        "acm2_trace_worst_abs": acm2["trace_vs_host_numpy"]["worst_abs"],
        "all_pass": ysu["verdict"] == "PASS" and acm2["verdict"] == "PASS",
    }


if __name__ == "__main__":
    summary = run()
    print(json.dumps(summary, indent=2))
    raise SystemExit(0 if summary["all_pass"] else 1)
