#!/usr/bin/env python3
"""Validate WSM3/WSM5 JAX ports against independent pristine-WRF oracles.

The references are short, isolated single-column savepoints generated by
``proofs/v060/oracle/build_wsm_sm_oracles.sh`` from the UNMODIFIED pristine WRF
tree at ``$WRF_PRISTINE_ROOT`` (default: sibling ``../wrf_pristine/WRF``). The fp64 savepoints are the binding
oracle for this gate. The canonical fp32 savepoints are recorded as shadow
metrics only; they are not used to pass or fail the port.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Callable

import numpy as np

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
sys.path.insert(0, str(ROOT / "src"))

os.environ.setdefault("JAX_PLATFORM_NAME", "cpu")
os.environ.setdefault("JAX_PLATFORMS", "cpu")

import jax  # noqa: E402

jax.config.update("jax_enable_x64", True)
import jax.numpy as jnp  # noqa: E402

from gpuwrf.physics.microphysics_wsm3 import wsm3_run  # noqa: E402
from gpuwrf.physics.microphysics_wsm5 import wsm5_run  # noqa: E402

SAVE_FP32 = HERE / "savepoints"
SAVE_FP64 = HERE / "savepoints_fp64"
# Pristine-WRF checkout root. Override with WRF_PRISTINE_ROOT; default = sibling of repo.
# expanduser() so a `~`-prefixed WRF_PRISTINE_ROOT is canonicalized to an absolute
# path in the emitted proof (matching the noahmp path-hygiene fix), rather than
# storing a literal `~/...` that path-form assertions would have to special-case.
WRF_SOURCE = Path(os.environ.get("WRF_PRISTINE_ROOT", str(ROOT.parent / "wrf_pristine" / "WRF"))).expanduser()
CASES = (1, 2, 3, 4, 5, 6)

# PREDECLARED TOLERANCES (frozen before report generation; do not loosen).
# These are fp64-vs-fp64 absolute gates. They allow only expected libm/order
# roundoff in exp/log-heavy saturation and fall-speed paths.
PREDECLARED_TOL = {
    "t_abs": 2.0e-8,
    "q_abs": 2.0e-11,
    "t_tendency_abs": 3.0e-10,
    "q_tendency_abs": 3.0e-13,
    "precip_abs": 1.0e-12,
    "sr_abs": 1.0e-12,
    "re_abs": 1.0e-10,
}

RE_FIELDS = (("re_cloud", "RE_CLOUD"), ("re_ice", "RE_ICE"), ("re_snow", "RE_SNOW"))


@dataclass(frozen=True)
class Scheme:
    key: str
    option: int
    label: str
    report_name: str
    q_fields: tuple[tuple[str, str, str], ...]
    run: Callable[[dict], dict[str, np.ndarray]]


def col(d: dict, name: str) -> np.ndarray:
    return np.asarray(d["columns"][name], dtype=np.float64)


def _as_batch(d: dict, name: str):
    return jnp.asarray(col(d, name)[None, :])


def run_wsm3_for(d: dict) -> dict[str, np.ndarray]:
    s = d["scalars"]
    out = wsm3_run(
        _as_batch(d, "T_IN"),
        _as_batch(d, "QV_IN"),
        _as_batch(d, "QC_IN"),
        _as_batch(d, "QR_IN"),
        _as_batch(d, "W_IN"),
        _as_batch(d, "DEN"),
        _as_batch(d, "P"),
        _as_batch(d, "DELZ"),
        s["DT"],
    )
    return {k: np.asarray(v, dtype=np.float64)[0] if np.ndim(v) else np.asarray(v, dtype=np.float64) for k, v in out.items()}


def run_wsm5_for(d: dict) -> dict[str, np.ndarray]:
    s = d["scalars"]
    out = wsm5_run(
        _as_batch(d, "T_IN"),
        _as_batch(d, "QV_IN"),
        _as_batch(d, "QC_IN"),
        _as_batch(d, "QR_IN"),
        _as_batch(d, "QI_IN"),
        _as_batch(d, "QS_IN"),
        _as_batch(d, "DEN"),
        _as_batch(d, "P"),
        _as_batch(d, "DELZ"),
        s["DT"],
    )
    return {k: np.asarray(v, dtype=np.float64)[0] if np.ndim(v) else np.asarray(v, dtype=np.float64) for k, v in out.items()}


SCHEMES: dict[str, Scheme] = {
    "wsm3": Scheme(
        key="wsm3",
        option=3,
        label="WSM3 (mp_physics=3)",
        report_name="wsm3_savepoint_parity_report.json",
        q_fields=(("qv", "QV_IN", "QV_OUT"), ("qc", "QC_IN", "QC_OUT"), ("qr", "QR_IN", "QR_OUT")),
        run=run_wsm3_for,
    ),
    "wsm5": Scheme(
        key="wsm5",
        option=4,
        label="WSM5 (mp_physics=4)",
        report_name="wsm5_savepoint_parity_report.json",
        q_fields=(
            ("qv", "QV_IN", "QV_OUT"),
            ("qc", "QC_IN", "QC_OUT"),
            ("qr", "QR_IN", "QR_OUT"),
            ("qi", "QI_IN", "QI_OUT"),
            ("qs", "QS_IN", "QS_OUT"),
        ),
        run=run_wsm5_for,
    ),
}


def max_metrics(a, b) -> dict[str, float]:
    aa = np.asarray(a, dtype=np.float64)
    bb = np.asarray(b, dtype=np.float64)
    diff = np.abs(aa - bb)
    scale = max(float(np.max(np.abs(bb))), 1.0e-30)
    return {
        "max_abs": float(np.max(diff)),
        "max_rel": float(np.max(diff) / scale),
        "scale": scale,
    }


def scalar_metrics(jax_value, oracle_value, tol: float, ref: str) -> dict[str, float | bool | str]:
    jv = float(np.asarray(jax_value, dtype=np.float64))
    ov = float(oracle_value)
    return {
        "ref": ref,
        "jax": jv,
        "oracle": ov,
        "abs_err": abs(jv - ov),
        "tol_abs": tol,
        "pass": bool(abs(jv - ov) <= tol),
    }


def field_gate(jax_arr, oracle_arr, tol: float, ref: str) -> dict[str, float | bool | str]:
    m = max_metrics(jax_arr, oracle_arr)
    return {
        "ref": ref,
        **m,
        "tol_abs": tol,
        "pass": bool(m["max_abs"] <= tol),
    }


def _read_json(path: Path) -> dict:
    with path.open() as fh:
        return json.load(fh)


def _read_checksums(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    out: list[dict[str, str]] = []
    for line in path.read_text().splitlines():
        parts = line.split(maxsplit=1)
        if len(parts) == 2:
            out.append({"sha256": parts[0], "file": parts[1]})
    return out


def run_case(scheme: Scheme, cid: int) -> tuple[bool, dict]:
    d64 = _read_json(SAVE_FP64 / f"{scheme.key}_case_{cid}.json")
    d32 = _read_json(SAVE_FP32 / f"{scheme.key}_case_{cid}.json")
    dt = float(d64["scalars"]["DT"])
    out = scheme.run(d64)
    fields: dict[str, dict] = {}
    passed = True

    rec = field_gate(out["t"], col(d64, "T_OUT"), PREDECLARED_TOL["t_abs"], "fp64")
    fields["t"] = rec
    passed = passed and bool(rec["pass"])

    t_tend_jax = (out["t"] - col(d64, "T_IN")) / dt
    t_tend_oracle = (col(d64, "T_OUT") - col(d64, "T_IN")) / dt
    rec = field_gate(t_tend_jax, t_tend_oracle, PREDECLARED_TOL["t_tendency_abs"], "fp64")
    fields["t_tendency"] = rec
    passed = passed and bool(rec["pass"])

    for leaf, in_name, out_name in scheme.q_fields:
        rec = field_gate(out[leaf], col(d64, out_name), PREDECLARED_TOL["q_abs"], "fp64")
        fields[leaf] = rec
        passed = passed and bool(rec["pass"])

        jax_tendency = (out[leaf] - col(d64, in_name)) / dt
        oracle_tendency = (col(d64, out_name) - col(d64, in_name)) / dt
        rec = field_gate(jax_tendency, oracle_tendency, PREDECLARED_TOL["q_tendency_abs"], "fp64")
        fields[f"{leaf}_tendency"] = rec
        passed = passed and bool(rec["pass"])

    for leaf, out_name in RE_FIELDS:
        rec = field_gate(out[leaf], col(d64, out_name), PREDECLARED_TOL["re_abs"], "fp64")
        shadow = max_metrics(out[leaf], col(d32, out_name))
        rec["vs_fp32_max_abs"] = shadow["max_abs"]
        rec["vs_fp32_max_rel"] = shadow["max_rel"]
        fields[leaf] = rec
        passed = passed and bool(rec["pass"])

    for leaf, scalar in (("rainncv", "RAINNCV"), ("snowncv", "SNOWNCV")):
        rec = scalar_metrics(out[leaf], d64["scalars"][scalar], PREDECLARED_TOL["precip_abs"], "fp64")
        shadow = scalar_metrics(out[leaf], d32["scalars"][scalar], PREDECLARED_TOL["precip_abs"], "fp32-shadow")
        rec["vs_fp32_abs_err"] = shadow["abs_err"]
        fields[leaf] = rec
        passed = passed and bool(rec["pass"])

    rec = scalar_metrics(out["sr"], d64["scalars"]["SR"], PREDECLARED_TOL["sr_abs"], "fp64")
    shadow = scalar_metrics(out["sr"], d32["scalars"]["SR"], PREDECLARED_TOL["sr_abs"], "fp32-shadow")
    rec["vs_fp32_abs_err"] = shadow["abs_err"]
    fields["sr"] = rec
    passed = passed and bool(rec["pass"])

    return bool(passed), {"pass": bool(passed), "fields": fields}


def build_report(scheme: Scheme) -> dict:
    cases = {}
    allpass = True
    for cid in CASES:
        ok, payload = run_case(scheme, cid)
        cases[str(cid)] = payload
        allpass = allpass and ok
        status = "PASS" if ok else "FAIL"
        print(f"=== {scheme.key.upper()} CASE {cid} -> {status} ===")
        for field, metrics in payload["fields"].items():
            if "max_abs" in metrics:
                print(
                    f"  {field:14s} [{metrics['ref']}] "
                    f"max_abs={metrics['max_abs']:.3e} max_rel={metrics['max_rel']:.3e} "
                    f"{'ok' if metrics['pass'] else 'FAIL'}"
                )
            else:
                print(
                    f"  {field:14s} [{metrics['ref']}] "
                    f"jax={metrics['jax']:.5e} oracle={metrics['oracle']:.5e} "
                    f"abs_err={metrics['abs_err']:.3e} {'ok' if metrics['pass'] else 'FAIL'}"
                )

    return {
        "schema": f"gpuwrf.v060.{scheme.key}_savepoint_parity.v1",
        "scheme": scheme.label,
        "oracle": {
            "prognostic_ref": (
                f"UNMODIFIED pristine WRF {WRF_SOURCE} phys/module_mp_{scheme.key}.F "
                "fp64 short single-column savepoints (proofs/v060/savepoints_fp64)"
            ),
            "canonical_fp32_shadow": "UNMODIFIED pristine WRF fp32 savepoints (proofs/v060/savepoints); metrics recorded only",
            "wrf_source": str(WRF_SOURCE),
            "no_self_compare": True,
            "short_run": "6 isolated 40-level single-column cases, one pristine-WRF scheme call per case",
            "source_checksums_fp64": _read_checksums(SAVE_FP64 / "wsm_sm_source_checksums.txt"),
            "source_checksums_fp32": _read_checksums(SAVE_FP32 / "wsm_sm_source_checksums.txt"),
        },
        "jax_precision": "fp64",
        "predeclared_tolerances": PREDECLARED_TOL,
        "overall_pass": bool(allpass),
        "notes": [
            "Final T/state fields and explicit per-second T/q tendencies are gated against the fp64 pristine-WRF oracle.",
            "Canonical fp32 WRF savepoints are included as shadow metrics only; they do not determine pass/fail.",
            "Tolerances were predeclared before writing this report and were not loosened after comparison.",
        ],
        "cases": cases,
    }


def write_report(scheme: Scheme) -> tuple[bool, Path]:
    report = build_report(scheme)
    out = HERE / scheme.report_name
    out.write_text(json.dumps(report, indent=2) + "\n")
    print(f"{scheme.key.upper()} OVERALL: {'PASS' if report['overall_pass'] else 'FAIL'}")
    print(f"wrote {out}")
    return bool(report["overall_pass"]), out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("schemes", nargs="*", choices=tuple(SCHEMES))
    args = parser.parse_args(argv)
    allpass = True
    for name in (args.schemes or tuple(SCHEMES)):
        ok, _ = write_report(SCHEMES[name])
        allpass = allpass and ok
    return 0 if allpass else 1


if __name__ == "__main__":
    raise SystemExit(main())
