#!/usr/bin/env python3
"""v0.13 Tier-3 SURFACE-LAYER + LSM operational fp64 pristine-WRF oracle.

Gates the OPERATIONAL, ``jax.jit``-traceable v0.13 Tier-3 surface/LSM kernels
against fp64 savepoints produced by standalone Fortran drivers compiled against
the UNMODIFIED pristine WRF sources (NOT a JAX self-compare):

* ``physics.lsm_slab.slab_columns``        <- ``phys/module_sf_slab.F`` (SLAB)
* ``physics.sfclay_old_mm5.sfclay_old_mm5_columns``
                                           <- ``phys/module_sf_sfclay.F`` (SFCLAY)
* ``physics.sfclay_gfs.sf_gfs_columns``    <- ``phys/module_sf_gfs.F`` (SF_GFS)

The savepoints + per-source SHA-256 + build manifests live under
``proofs/v013/savepoints/surface_lsm/fp64`` and are regenerated by the
``proofs/v013/oracle/surface_lsm/*_build_and_run.sh`` scripts (conda ``wrfbuild``
gfortran, ``-fdefault-real-8 -fdefault-double-8``). The batched kernels are
exercised through ``jax.jit`` over the full case batch to prove the operational
path is genuinely jit/vmap-traceable.

Run (CPU, fp64; the GPU is owned by another lane):

    taskset -c 0-3 env JAX_PLATFORMS=cpu CUDA_VISIBLE_DEVICES= PYTHONPATH=src \\
        python proofs/v013/t3_surface_lsm_oracle.py

Writes ``proofs/v013/t3_surface_lsm_oracle.json``.
"""

from __future__ import annotations

import json
import os
import subprocess
from pathlib import Path

os.environ.setdefault("JAX_PLATFORM_NAME", "cpu")
os.environ.setdefault("JAX_PLATFORMS", "cpu")

import jax
import jax.numpy as jnp
import numpy as np

jax.config.update("jax_enable_x64", True)

from gpuwrf.physics.lsm_slab import slab_columns, nsoil_substeps
from gpuwrf.physics.sfclay_old_mm5 import sfclay_old_mm5_columns
from gpuwrf.physics.sfclay_gfs import sf_gfs_columns


ROOT = Path(__file__).resolve().parents[2]
SP = ROOT / "proofs" / "v013" / "savepoints" / "surface_lsm" / "fp64"
REPORT = Path(__file__).resolve().parent / "t3_surface_lsm_oracle.json"

# PREDECLARED fp64 operational-parity tolerances.
ABS_TOL = 5.0e-9
REL_TOL = 5.0e-10
REL_FLOOR = 1.0e-30

CASES = (1, 2, 3, 4, 5)


def _A(d):
    return jnp.asarray(d, jnp.float64)


def _metric(actual, expected):
    a = np.asarray(actual, dtype=np.float64)
    b = np.asarray(expected, dtype=np.float64)
    abs_err = np.abs(a - b)
    max_abs = float(np.max(abs_err))
    scale = max(float(np.max(np.abs(b))), REL_FLOOR)
    max_rel = max_abs / scale
    argmax = int(np.argmax(abs_err))
    return {
        "jax": float(np.ravel(a)[argmax]),
        "oracle": float(np.ravel(b)[argmax]),
        "max_abs": max_abs,
        "max_rel": float(max_rel),
        "pass": bool(max_abs <= ABS_TOL or max_rel <= REL_TOL),
    }


def _load(prefix: str, case: int) -> dict:
    with (SP / f"{prefix}_case_{case}.json").open(encoding="utf-8") as fh:
        return json.load(fh)


def _read_checksums(name: str) -> list[str]:
    p = SP / name
    return p.read_text(encoding="utf-8").splitlines() if p.exists() else []


# --------------------------------------------------------------------------- #
# Slab thermal-diffusion LSM (sf_surface_physics=1)                           #
# --------------------------------------------------------------------------- #
_SLAB_FIELDS = {
    "TSK": "tsk", "HFX": "hfx", "QFX": "qfx", "LH": "lh",
    "QSFC": "qsfc", "CHKLOWQ": "chklowq", "CAPG": "capg",
}


def _run_slab() -> dict:
    fn = jax.jit(slab_columns, static_argnames=("nsoil_steps", "ifsnow"))
    cases = []
    for c in CASES:
        d = _load("slab", c)
        col = d["columns"]; s = d["scalars"]; v = d["vectors"]
        zs = _A(v["ZS"]); dzs = _A(v["DZS"])
        tslb_in = _A(d["soil"]["TSLB_IN"])
        nss = nsoil_substeps(float(v["DZS"][0]), float(s["DELTSM"]))
        out = fn(
            _A(col["T"]), _A(col["QV"]), _A(col["P"]), _A(col["FLHC"]), _A(col["FLQC"]),
            _A(col["PSFC"]), _A(col["XLAND"]), _A(col["TSK_IN"]), tslb_in, _A(col["MAVAIL"]),
            _A(col["GSW"]), _A(col["GLW"]), _A(col["HFX_IN"]), _A(col["QFX_IN"]),
            jnp.zeros_like(_A(col["TSK_IN"])),   # lh_in (driver init LH=0)
            zs=zs, dzs=dzs, thc=_A(col["THC"]), tmn=_A(col["TMN"]),
            emiss=_A(col["EMISS"]), snowc=_A(col["SNOWC"]),
            deltsm=float(s["DELTSM"]), nsoil_steps=nss, ifsnow=int(s["IFSNOW"]),
        )
        out = {k: np.asarray(val) for k, val in out.items()}
        fields = {name: _metric(out[key], col[name]) for name, key in _SLAB_FIELDS.items()}
        fields["TSLB"] = _metric(out["tslb"], d["soil"]["TSLB"])
        case = {"case": c, "regime": s["REGIME"], "nsoil_steps": nss, "fields": fields}
        case["pass"] = bool(all(m["pass"] for m in fields.values()))
        cases.append(case)
    return {
        "scheme": "thermal-diffusion 5-layer slab LSM (sf_surface_physics=1)",
        "operational_kernel": "gpuwrf.physics.lsm_slab.slab_columns (jit/vmap-traceable)",
        "operational_status": (
            "REFERENCE_ONLY -- fp64 oracle-validated, but fail-closed in the operational "
            "scan until the slab LSM hook (TSLB land carry + GSW/GLW forcing + TMN/THC/EMISS "
            "statics) is threaded; selectable for a single-column reference comparison."
        ),
        "wrf_source": "/home/enric/src/wrf_pristine/WRF/phys/module_sf_slab.F",
        "source_checksums_sha256": _read_checksums("slab_wrf_source_checksums.txt"),
        "cases": cases,
        "pass": bool(all(c["pass"] for c in cases)),
    }


# --------------------------------------------------------------------------- #
# Old-MM5 surface layer (sf_sfclay_physics=91)                                #
# --------------------------------------------------------------------------- #
_OLDMM5_FIELDS = {
    "UST": "ust", "ZNT": "znt", "MOL": "mol", "RMOL": "rmol", "REGIME": "regime",
    "PSIM": "psim", "PSIH": "psih", "FM": "fm", "FH": "fh", "QSFC": "qsfc",
    "QGH": "qgh", "CPM": "cpm", "HFX": "hfx", "QFX": "qfx", "LH": "lh",
    "FLHC": "flhc", "FLQC": "flqc", "CHS": "chs", "CHS2": "chs2", "CQS2": "cqs2",
    "U10": "u10", "V10": "v10", "TH2": "th2", "T2": "t2", "Q2": "q2",
    "BR": "br", "WSPD": "wspd", "GZ1OZ0": "gz1oz0", "ZOL": "zol",
}


def _run_old_mm5() -> dict:
    fn = jax.jit(sfclay_old_mm5_columns, static_argnames=("isfflx",))
    cases = []
    for c in CASES:
        d = _load("sfclay_old_mm5", c)
        col = d["columns"]; s = d["scalars"]
        out = fn(
            _A(col["U"]), _A(col["V"]), _A(col["T"]), _A(col["QV"]), _A(col["P"]),
            _A(col["DZ"]), _A(col["PSFC"]), _A(col["TSK"]), _A(col["XLAND"]),
            _A(col["ZNT_IN"]), _A(col["UST_IN"]), _A(col["MOL_IN"]), _A(col["QSFC_IN"]),
            _A(col["PBLH"]), _A(col["MAVAIL"]), _A(col["LAKEMASK"]), _A(col["DX"]),
            _A(col["HFX_IN"]), _A(col["QFX_IN"]), isfflx=1,
        )
        out = {k: np.asarray(val) for k, val in out.items()}
        fields = {name: _metric(out[key], col[name]) for name, key in _OLDMM5_FIELDS.items()}
        case = {"case": c, "regime": s["REGIME"], "fields": fields}
        case["pass"] = bool(all(m["pass"] for m in fields.values()))
        cases.append(case)
    return {
        "scheme": "old-MM5 Monin-Obukhov surface layer (sf_sfclay_physics=91)",
        "operational_kernel": "gpuwrf.physics.sfclay_old_mm5.sfclay_old_mm5_columns (jit/vmap-traceable)",
        "operational_status": (
            "IMPLEMENTED -- scan-wired via coupling.scan_adapters.sfclay_old_mm5_adapter "
            "(SFCLAY_SCAN_ADAPTERS[91]); writes the B2 kinematic surface flux handles."
        ),
        "wrf_source": "/home/enric/src/wrf_pristine/WRF/phys/module_sf_sfclay.F",
        "source_checksums_sha256": _read_checksums("sfclay_old_mm5_wrf_source_checksums.txt"),
        "cases": cases,
        "pass": bool(all(c["pass"] for c in cases)),
    }


# --------------------------------------------------------------------------- #
# NCEP-GFS surface layer (sf_sfclay_physics=3)                                #
# --------------------------------------------------------------------------- #
_GFS_FIELDS = {
    "UST": "ust", "ZNT": "znt", "CHS": "chs", "CHS2": "chs2", "CQS2": "cqs2",
    "CPM": "cpm", "PSIM": "psim", "PSIH": "psih", "QGH": "qgh", "QSFC": "qsfc",
    "U10": "u10", "V10": "v10", "WSPD": "wspd", "BR": "br", "GZ1OZ0": "gz1oz0",
    "FLHC": "flhc", "FLQC": "flqc", "HFX": "hfx", "QFX": "qfx", "LH": "lh",
}


def _run_gfs() -> dict:
    fn = jax.jit(sf_gfs_columns, static_argnames=("isfflx",))
    cases = []
    for c in CASES:
        d = _load("sfclay_gfs", c)
        col = d["columns"]; s = d["scalars"]
        out = fn(
            _A(col["U"]), _A(col["V"]), _A(col["T"]), _A(col["QV"]), _A(col["P"]),
            _A(col["PSFC"]), _A(col["TSK"]), _A(col["XLAND"]), _A(col["ZNT_IN"]),
            _A(col["UST_IN"]), isfflx=1,
        )
        out = {k: np.asarray(val) for k, val in out.items()}
        fields = {name: _metric(out[key], col[name]) for name, key in _GFS_FIELDS.items()}
        case = {"case": c, "regime": s["REGIME"], "fields": fields}
        case["pass"] = bool(all(m["pass"] for m in fields.values()))
        cases.append(case)
    return {
        "scheme": "NCEP-GFS Monin-Obukhov surface layer (sf_sfclay_physics=3)",
        "operational_kernel": "gpuwrf.physics.sfclay_gfs.sf_gfs_columns (jit/vmap-traceable)",
        "operational_status": (
            "IMPLEMENTED -- scan-wired via coupling.scan_adapters.gfs_sfclay_adapter "
            "(SFCLAY_SCAN_ADAPTERS[3]); writes the B2 kinematic surface flux handles. "
            "fpvs reproduced faithfully (the same 7501-node Clausius-Clapeyron table)."
        ),
        "wrf_source": "/home/enric/src/wrf_pristine/WRF/phys/module_sf_gfs.F (+ module_gfs_funcphys/physcons/machine)",
        "source_checksums_sha256": _read_checksums("sfclay_gfs_wrf_source_checksums.txt"),
        "cases": cases,
        "pass": bool(all(c["pass"] for c in cases)),
    }


def _git_head() -> str:
    return subprocess.check_output(
        ["git", "-C", str(ROOT), "rev-parse", "HEAD"], text=True
    ).strip()


def build_report() -> dict:
    schemes = {
        "slab_lsm": _run_slab(),
        "old_mm5_sfclay": _run_old_mm5(),
        "gfs_sfclay": _run_gfs(),
    }
    overall = all(v["pass"] for v in schemes.values())
    return {
        "schema": "gpuwrf.v013.t3_surface_lsm_operational_fp64_oracle.v1",
        "tier": "v0.13 Tier-3 surface-layer + LSM (first batch)",
        "verdict": "PASS" if overall else "FAIL",
        "overall_pass": bool(overall),
        "oracle": {
            "type": "standalone single-column Fortran drivers linked against the "
                    "UNMODIFIED pristine WRF module_sf_{slab,sfclay,gfs}.F (NOT a JAX "
                    "self-compare); fp64 (-fdefault-real-8 -fdefault-double-8).",
            "savepoints": str(SP.relative_to(ROOT)),
            "drivers": "proofs/v013/oracle/surface_lsm/*_oracle_driver.f90 (+ *_build_and_run.sh)",
            "full_wrf_exe": False,
            "self_compare": False,
        },
        "jax_precision": "fp64",
        "jax_platform": jax.default_backend(),
        "git_head": _git_head(),
        "predeclared_tolerances": {"abs": ABS_TOL, "rel": REL_TOL, "relative_floor": REL_FLOOR},
        "schemes": schemes,
    }


def main() -> int:
    report = build_report()
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    with REPORT.open("w", encoding="utf-8") as fh:
        json.dump(report, fh, indent=2, sort_keys=True)
        fh.write("\n")
    print(f"verdict={report['verdict']} -> {REPORT}")
    for name, sch in report["schemes"].items():
        worst = max(
            max(m["max_abs"] for m in c["fields"].values()) for c in sch["cases"]
        )
        print(f"  {name:18s} {'PASS' if sch['pass'] else 'FAIL'}  worst |jax-oracle|={worst:.3e}")
    return 0 if report["overall_pass"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
