"""WRF v4 land history metadata, pinned from the real WN3 CPU inventory.

Source: 20260227_18z_a1 d01 t0, cross-checked by test_writer_land_history.
"""
LAND_HISTORY_METADATA = {
    'ACCANHS': ('accumulated canopy storage change', 'KJ/m2'),
    'ACDEWC': ('Accumulated canopy dew', 'mm'),
    'ACDRIPR': ('Accumulated canopy rain drip', 'mm'),
    'ACDRIPS': ('Accumulated canopy snow drip', 'mm'),
    'ACECAN': ('Accumulated evaporation of intercepted water', 'mm'),
    'ACEDIR': ('Accumulated ground surface evaporation', 'mm'),
    'ACEFLXB': ('accumulated bottom soil heat flux', 'kJ/m2'),
    'ACETLSM': ('Accumulated evaporation', 'mm'),
    'ACETRAN': ('Accumulated transpiration', 'mm'),
    'ACEVAC': ('Accumulated canopy evaporation', 'mm'),
    'ACEVB': ('Accumulated latent heat flux at bare fraction', 'kJ/m2'),
    'ACEVC': ('Accumulated canopy evaporation', 'kJ/m2'),
    'ACEVG': ('Accumulated latent heat flux: ground to canopy', 'kJ/m2'),
    'ACFROC': ('Accumulated canopy frost', 'mm'),
    'ACFRZC': ('Accumulated canopy liquid freeze', 'mm'),
    'ACGHB': ('Accumulated heat flux into soil at bare fraction', 'kJ/m2'),
    'ACGHFLSM': ('accumulated total ground heat flux', 'kJ/m2'),
    'ACGHV': ('Accumulated heat flux into soil under canopy', 'kJ/m2'),
    'ACGRDFLX': ('ACCUMULATED GROUND HEAT FLUX', 'J m-2'),
    'ACHFX': ('ACCUMULATED UPWARD HEAT FLUX AT THE SURFACE', 'J m-2'),
    'ACINTR': ('Accumulated canopy rain interception', 'mm'),
    'ACINTS': ('Accumulated canopy snow interception', 'mm'),
    'ACIRB': ('Accumulated net longwave at bare fraction', 'kJ/m2'),
    'ACIRC': ('Accumulated net longwave in canopy', 'kJ/m2'),
    'ACIRG': ('Accumulated net longwave below canopy surface', 'kJ/m2'),
    'ACLHF': ('ACCUMULATED UPWARD LATENT HEAT FLUX AT THE SURFACE', 'J m-2'),
    'ACLHFLSM': ('accumulated total latent heat flux', 'kJ/m2'),
    'ACLWDNB': ('ACCUMULATED DOWNWELLING LONGWAVE FLUX AT BOTTOM', 'J m-2'),
    'ACLWDNBC': ('ACCUMULATED DOWNWELLING CLEAR SKY LONGWAVE FLUX AT BOTTOM', 'J m-2'),
    'ACLWDNLSM': ('Accumulated longwave down at LSM', 'kJ/m2'),
    'ACLWDNT': ('ACCUMULATED DOWNWELLING LONGWAVE FLUX AT TOP', 'J m-2'),
    'ACLWDNTC': ('ACCUMULATED DOWNWELLING CLEAR SKY LONGWAVE FLUX AT TOP', 'J m-2'),
    'ACLWUPB': ('ACCUMULATED UPWELLING LONGWAVE FLUX AT BOTTOM', 'J m-2'),
    'ACLWUPBC': ('ACCUMULATED UPWELLING CLEAR SKY LONGWAVE FLUX AT BOTTOM', 'J m-2'),
    'ACLWUPLSM': ('Accumulated longwave up at LSM', 'kJ/m2'),
    'ACLWUPT': ('ACCUMULATED UPWELLING LONGWAVE FLUX AT TOP', 'J m-2'),
    'ACLWUPTC': ('ACCUMULATED UPWELLING CLEAR SKY LONGWAVE FLUX AT TOP', 'J m-2'),
    'ACMELTC': ('Accumulated canopy snow melt', 'mm'),
    'ACPAHB': ('Accumulated precipitation advected energy to bare ground', 'kJ/m2'),
    'ACPAHG': ('Accumulated precipitation advected energy to below canopy', 'kJ/m2'),
    'ACPAHLSM': ('accumulated total precip heat flux', 'kJ/m2'),
    'ACPAHV': ('Accumulated precipitation advected energy to vegetation', 'kJ/m2'),
    'ACPONDING': ('Accumulated surface ponding from complete pack melt', 'mm'),
    'ACQLAT': ('accumulated lateral flow', 'mm'),
    'ACQRF': ('accumulated baseflow', 'mm'),
    'ACRAINLSM': ('Accumulated liquid precipitation into LSM', 'mm'),
    'ACRAINSNOW': ('accumulated rain on snow pack', 'mm'),
    'ACRUNSB': ('Accumulated subsurface runoff', 'mm'),
    'ACRUNSF': ('Accumulated surface runoff', 'mm'),
    'ACSAGB': ('Accumulated solar radiation absorbed at bare fraction', 'kJ/m2'),
    'ACSAGV': ('Accumulated solar radiation absorbed at vegetated fraction', 'kJ/m2'),
    'ACSAV': ('Accumulated solar rad absorbed by vegetated fraction', 'kJ/m2'),
    'ACSHB': ('Accumulated sensible heat flux at bare fraction', 'kJ/m2'),
    'ACSHC': ('Accumulated sensible heat flux: canopy to atmosphere', 'kJ/m2'),
    'ACSHFLSM': ('accumulated total sensible heat flux', 'kJ/m2'),
    'ACSHG': ('Accumulated sensible heat flux: ground to canopy', 'kJ/m2'),
    'ACSNBOT': ('Accumulated total liquid water (melt + rain through pack) out of snowpack bottom', 'mm'),
    'ACSNFRO': ('Accumulated snow pack frost', 'mm'),
    'ACSNMELT': ('Accumulated snowmelt due to phase change', 'mm'),
    'ACSNOM': ('ACCUMULATED MELTED SNOW', 'kg m-2'),
    'ACSNOWLSM': ('Accumulated frozen precipitation into LSM', 'mm'),
    'ACSNSUB': ('Accumulated snow pack sublimation', 'mm'),
    'ACSUBC': ('Accumulated canopy sublimation', 'mm'),
    'ACSWDNB': ('ACCUMULATED DOWNWELLING SHORTWAVE FLUX AT BOTTOM', 'J m-2'),
    'ACSWDNBC': ('ACCUMULATED DOWNWELLING CLEAR SKY SHORTWAVE FLUX AT BOTTOM', 'J m-2'),
    'ACSWDNLSM': ('Accumulated shortwave down at LSM', 'kJ/m2'),
    'ACSWDNT': ('ACCUMULATED DOWNWELLING SHORTWAVE FLUX AT TOP', 'J m-2'),
    'ACSWDNTC': ('ACCUMULATED DOWNWELLING CLEAR SKY SHORTWAVE FLUX AT TOP', 'J m-2'),
    'ACSWUPB': ('ACCUMULATED UPWELLING SHORTWAVE FLUX AT BOTTOM', 'J m-2'),
    'ACSWUPBC': ('ACCUMULATED UPWELLING CLEAR SKY SHORTWAVE FLUX AT BOTTOM', 'J m-2'),
    'ACSWUPLSM': ('Accumulated shortwave up at LSM', 'kJ/m2'),
    'ACSWUPT': ('ACCUMULATED UPWELLING SHORTWAVE FLUX AT TOP', 'J m-2'),
    'ACSWUPTC': ('ACCUMULATED UPWELLING CLEAR SKY SHORTWAVE FLUX AT TOP', 'J m-2'),
    'ACTHROR': ('Accumulated rain throughfall', 'mm'),
    'ACTHROS': ('Accumulated snow throughfall', 'mm'),
    'ACTR': ('Accumulated transpiration', 'kJ/m2'),
    'ALBBCK': ('BACKGROUND ALBEDO', ''),
    'ALBEDO': ('ALBEDO', '-'),
    'ALBOLD': ('snow albedo at last timestep', '-'),
    'APAR': ('photosyn active energy by canopy', 'W/m2'),
    'CANICE': ('intercepted ice mass', 'mm'),
    'CANLIQ': ('intercepted liquid water', 'mm'),
    'CANWAT': ('CANOPY WATER', 'kg m-2'),
    'CH': ('surf. exchange coeff. for heat', 'm/s'),
    'CHB': ('bare-ground heat exchange coefficient', 'm/s'),
    'CHB2': ('under canopy exchange coefficient', 'm/s'),
    'CHLEAF': ('leaf exchange coefficient', 'm/s'),
    'CHUC': ('under canopy exchange coefficient', 'm/s'),
    'CHV': ('vegetated heat exchange coefficient', 'm/s'),
    'CHV2': ('leaf exchange coefficient', 'm/s'),
    'CM': ('surf. exchange coeff. for momentum', 'm/s'),
    'CON': ('OROGRAPHIC CONVEXITY', ''),
    'EAH': ('canopy air vapor pressure', 'pa'),
    'ECAN': ('evaporation of intercepted water', 'mm/s'),
    'EDIR': ('ground surface evaporation rate', 'mm/s'),
    'EMISS': ('SURFACE EMISSIVITY', ''),
    'ETRAN': ('transpiration rate', 'mm/s'),
    'EVB': ('latent heat flux: bare grnd to atmo', 'W/m2'),
    'EVC': ('canopy evaporation', 'W/m2'),
    'EVG': ('latent heat flux: ground to canopy', 'W/m2'),
    'FASTCP': ('short-lived carbon', 'g/m2'),
    'FIRA': ('total net longwave rad', 'W/m2'),
    'FORCPLSM': ('lowest model P into LSM', 'Pa'),
    'FORCQLSM': ('lowest model Q into LSM', 'kg/kg'),
    'FORCTLSM': ('lowest model T into LSM', 'K'),
    'FORCWLSM': ('lowest model wind speed into LSM', 'm/s'),
    'FORCZLSM': ('lowest model Z into LSM', 'm'),
    'FSA': ('total absorbed solar radiation', 'W/m2'),
    'FVEG': ('Noah-MP vegetation fraction', ''),
    'FWET': ('wetted or snowed canopy fraction', '-'),
    'GHB': ('heat flux into soil: bare fraction', 'W/m2'),
    'GHV': ('heat flux into soil: under canopy', 'W/m2'),
    'GRDFLX': ('GROUND HEAT FLUX', 'W m-2'),
    'IRB': ('net longwave at bare fraction surface', 'W/m2'),
    'IRC': ('net longwave in canopy', 'W/m2'),
    'IRG': ('net longwave at below canopy surface', 'W/m2'),
    'ISLTYP': ('DOMINANT SOIL CATEGORY', ''),
    'ISNOW': ('no. of snow layer', 'm3 m-3'),
    'IVGTYP': ('DOMINANT VEGETATION CATEGORY', ''),
    'VEGFRA': ('VEGETATION FRACTION', ''),
    'LAI': ('LEAF AREA INDEX', 'm-2/m-2'),
    'LFMASS': ('leaf mass', 'g/m2'),
    'OA1': ('ASYMMETRY OF SUBGRID-SCALE OROGRAPHY FOR WESTERLY FLOW', ''),
    'OA2': ('ASYMMETRY OF SUBGRID-SCALE OROGRAPHY FOR SOUTHERLY FLOW', ''),
    'OA3': ('ASYMMETRY OF SUBGRID-SCALE OROGRAPHY FOR SOUTH-WESTERLY FLOW', ''),
    'OA4': ('ASYMMETRY OF SUBGRID-SCALE OROGRAPHY FOR NORTH-WESTERLY FLOW', ''),
    'OL1': ('NON-DIMENSIONAL EFFECTIVE OROGRAPHIC LENGTH FOR WESTERLY FLOW', ''),
    'OL2': ('NON-DIMENSIONAL EFFECTIVE OROGRAPHIC LENGTH FOR SOUTHERLY FLOW', ''),
    'OL3': ('NON-DIMENSIONAL EFFECTIVE OROGRAPHIC LENGTH FOR SOUTH-WESTERLY FLOW', ''),
    'OL4': ('NON-DIMENSIONAL EFFECTIVE OROGRAPHIC LENGTH FOR NORTH-WESTERLY FLOW', ''),
    'PSN': ('total photosynthesis', 'umol co2/m2/s'),
    'Q2B': ('2 meter mixing ratio over bare ground', 'kg kg-1'),
    'Q2V': ('2 meter mixing ratio over canopy', 'kg kg-1'),
    'RSSHA': ('shaded stomatal resistance', 's/m'),
    'RSSUN': ('sunlit stomatal resistance', 's/m'),
    'RTMASS': ('mass of fine roots', 'g/m2'),
    'RUNSB': ('subsurface runoff', 'mm/s'),
    'RUNSF': ('surface runoff', 'mm/s'),
    'SAG': ('solar rad absorbed by ground', 'W/m2'),
    'SAV': ('solar rad absorbed by veg', 'W/m2'),
    'SFROFF': ('SURFACE RUNOFF', 'mm'),
    'SH2O': ('SOIL LIQUID WATER', 'm3 m-3'),
    'SHB': ('sensible heat flux: bare grnd to atmo', 'W/m2'),
    'SHC': ('sensible heat flux: leaf to canopy', 'W/m2'),
    'SHDAVG': ('ANNUAL AVG VEG FRACTION', ''),
    'SHDMAX': ('ANNUAL MAX VEG FRACTION', ''),
    'SHDMIN': ('ANNUAL MIN VEG FRACTION', ''),
    'SHG': ('sensible heat flux: ground to canopy', 'W/m2'),
    'SMOIS': ('SOIL MOISTURE', 'm3 m-3'),
    'SNEQVO': ('snow mass at last time step', 'mm'),
    'SNICE': ('snow layer ice', 'mm'),
    'SNLIQ': ('snow layer liquid', 'mm'),
    'SNOALB': ('ANNUAL MAX SNOW ALBEDO IN FRACTION', ''),
    'SNOW': ('SNOW WATER EQUIVALENT', 'kg m-2'),
    'SNOWC': ('FLAG INDICATING SNOW COVERAGE (1 FOR SNOW COVER)', ''),
    'SNOWENERGY': ('energy content in snow relative to 273.16', 'kJ/m2'),
    'SNOWH': ('PHYSICAL SNOW DEPTH', 'm'),
    'SOILENERGY': ('energy content in soil relative to 273.16', 'kJ/m2'),
    'STBLCP': ('stable carbon pool', 'g/m2'),
    'STMASS': ('stem mass', 'g/m2'),
    'T2B': ('2 meter temperature over bare ground', 'K'),
    'T2V': ('2 meter temperature over canopy', 'K'),
    'TAH': ('canopy air temperature', 'K'),
    'TAUSS': ('non-dimensional snow age', ''),
    'TG': ('bulk ground temperature', 'K'),
    'TMN': ('SOIL TEMPERATURE AT LOWER BOUNDARY', 'K'),
    'TR': ('transpiration', 'W/m2'),
    'TRAD': ('surface radiative temperature', 'K'),
    'TSLB': ('SOIL TEMPERATURE', 'K'),
    'TSNO': ('snow temperature', 'K'),
    'TV': ('vegetation leaf temperature', 'K'),
    'UDROFF': ('UNDERGROUND RUNOFF', 'mm'),
    'VAR': ('STANDARD DEVIATION OF SUBGRID-SCALE OROGRAPHY', 'm'),
    'VAR_SSO': ('variance of subgrid-scale orography', 'm2'),
    'WOOD': ('mass of wood', 'g/m2'),
    'XSAI': ('stem area index', '-'),
    'ZSNSO': ('layer-bottom depth from snow surf', 'm'),
    'SMCWTD': ('deep soil moisture', 'm3 m-3'),
    'CHSTAR': ('dummy exchange coefficient', 'm/s'),
    'TGV': ('ground temp. under canopy', 'K'),
    'TGB': ('bare ground temperature', 'K'),
    'BGAP': ('between canopy gap', 'fraction'),
    'WGAP': ('within canopy gap', 'fraction'),
    'GDD': ('growing degree days', ''),
    'GPP': ('gross primary productivity', 'g/m2/s C'),
    'GRAIN': ('mass of grain', 'g/m2'),
    'NEE': ('net ecosystem exchange', 'g/m2/s CO2'),
    'NPP': ('net primary productivity', 'g/m2/s C'),
    'WA': ('water in the acquifer', 'mm'),
    'WT': ('groundwater storage', 'mm'),
    'ZWT': ('water table depth', 'm'),
    'WSLAKE': ('lake water storage', 'mm'),
}
