#!/usr/bin/env bash
# v0.21.0 FUSED+AOT 9-NEST STRESS gate (the mandatory stress case alongside the 3-dom).
# Same structure as run_v0210_fused_aot_gate.sh but MAXDOM=9 (all-domain nest), full cores
# (big fused cold compile ~60GB), longer lock timeout. Cold capture -> serialize fused blob;
# fresh warm -> load it (must: fused/* loaded=aot_blob, no jit_fused re-lower, bit-identical,
# s/step no-regression vs the cold-compiled fused of THIS run).
set -euo pipefail

mkdir -p proofs/v021/canary_gate/logs

scripts/with_gpu_lock.sh --timeout 14400 --label fused-aot-9nest-gate -- timeout 4h bash -lc '
set -euo pipefail

LOG1=proofs/v021/canary_gate/logs/fused_aot_9nest_capture.log
LOG2=proofs/v021/canary_gate/logs/fused_aot_9nest_warm_load.log
VALIDATION=proofs/v021/canary_gate/logs/fused_aot_9nest_validation.json
REF=proofs/v021/canary_gate/ts_proof_fused_aot_9nest_capture/warmK_state_digest.json
EXPECT_FUSED_PHASES=${CANARY_EXPECT_FUSED_PHASES:-2}
MAX_FUSED_PHASES=${CANARY_MAX_FUSED_PHASES:-4}
MAX_S_PER_FC_HOUR=${CANARY_MAX_S_PER_FC_HOUR:-1200}
RUN_ID=${CANARY_RUN_ID:-$(date -u +%Y%m%dT%H%M%SZ)}
CACHE_DIR=${CANARY_JAX_CACHE_DIR:-/tmp/gpuwrf_v0210_fused_aot_9nest_gate_${RUN_ID}}
CACHE_MODE=fresh
if [[ -n "${CANARY_JAX_CACHE_DIR:-}" ]]; then
  CACHE_MODE=override
elif [[ -e "$CACHE_DIR" ]]; then
  echo "Refusing to use existing autogenerated cache dir: $CACHE_DIR" >&2
  exit 2
fi
mkdir -p "$CACHE_DIR"
rm -f "$LOG1" "$LOG2" "$VALIDATION"

COMMON_ENV=(
  PYTHONPATH=src
  JAX_ENABLE_X64=true
  XLA_PYTHON_CLIENT_PREALLOCATE=false
  JAX_COMPILATION_CACHE_DIR="$CACHE_DIR"
  GPUWRF_JAX_CACHE_DIR="$CACHE_DIR"
  GPUWRF_CANAIRY_ROOT=<DATA_ROOT>/canairy_meteo
  CANARY_INPUT_DIR=${CANARY_INPUT_DIR:-<DATA_ROOT>/wrf_downscale/runs/20240901/cpu}
  CANARY_MAXDOM=9
  MAXDOM=9
  CANARY_KWARM=${CANARY_KWARM:-2}
  CANARY_SINGLE_SHAPE_TIMING=1
  CANARY_FIXED_ROOT_STEPS=${CANARY_FIXED_ROOT_STEPS:-1}
  CANARY_FIXED_REPEATS=${CANARY_FIXED_REPEATS:-2}
  GPUWRF_NESTED_AOT=1
  GPUWRF_NESTED_PARALLEL_COMPILE=0
)

printf "MARKER:GATE_CACHE cache_dir=%s cache_mode=%s expect_fused_phases=%s max_fused_phases=%s max_s_per_fc_hour=%s\n" \
  "$CACHE_DIR" "$CACHE_MODE" "$EXPECT_FUSED_PHASES" "$MAX_FUSED_PHASES" "$MAX_S_PER_FC_HOUR" | tee "$LOG1"
env "${COMMON_ENV[@]}" CANARY_TAG=fused_aot_9nest_capture \
  python proofs/v021/canary_gate/perstep_timing_driver.py 2>&1 | tee -a "$LOG1"
if rg -q "DRIVER RAISED" "$LOG1"; then
  exit 1
fi

test -f "$REF"

printf "MARKER:GATE_CACHE cache_dir=%s cache_mode=%s expect_fused_phases=%s max_fused_phases=%s max_s_per_fc_hour=%s\n" \
  "$CACHE_DIR" "$CACHE_MODE" "$EXPECT_FUSED_PHASES" "$MAX_FUSED_PHASES" "$MAX_S_PER_FC_HOUR" | tee "$LOG2"
env "${COMMON_ENV[@]}" CANARY_TAG=fused_aot_9nest_warm \
  CANARY_REF_DIGEST="$REF" JAX_LOG_COMPILES=1 \
  python proofs/v021/canary_gate/perstep_timing_driver.py 2>&1 | tee -a "$LOG2"
if rg -q "DRIVER RAISED" "$LOG2"; then
  exit 1
fi

python proofs/v021/canary_gate/validate_fused_aot_9nest_gate.py \
  --cold-log "$LOG1" \
  --warm-log "$LOG2" \
  --output "$VALIDATION" \
  --expect-fused-phases "$EXPECT_FUSED_PHASES" \
  --max-fused-phases "$MAX_FUSED_PHASES" \
  --max-s-per-fc-hour "$MAX_S_PER_FC_HOUR"
'
