"""v0.13 Tier3 GSFC (Chou-Suarez) shortwave (ra_sw_physics=2) savepoint parity.

Validates the JAX GSFC SW port against the unmodified WRF module_ra_gsfcsw.F
oracle savepoints generated by proofs/radiation/oracle/gsfcsw_build_and_run.sh.
The fp64 oracle build must match to deep round-off; the canonical fp32 build is
bounded by the predeclared parity tolerances. NOT a self-compare: the reference
is the real pristine-WRF GSFCSWRAD source compiled standalone.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

import pytest

os.environ.setdefault("JAX_PLATFORM_NAME", "cpu")
os.environ.setdefault("JAX_PLATFORMS", "cpu")

import jax  # noqa: E402

jax.config.update("jax_enable_x64", True)
import jax.numpy as jnp  # noqa: E402
import numpy as np  # noqa: E402

from gpuwrf.physics.ra_sw_gsfc import GsfcSWColumnState, solve_gsfc_sw_column  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
SAVE_FP32 = ROOT / "proofs" / "radiation" / "savepoints_gsfcsw"
SAVE_FP64 = ROOT / "proofs" / "radiation" / "savepoints_gsfcsw_fp64"
CASES = (1, 2, 3, 4, 5, 6, 7)

# Predeclared tolerances (mirror proofs/v013/t3_radiation_oracle.py).
TOL = {
    "fp32": dict(rth_abs=1.0e-6, rth_rel=5.0e-3, gsw_rel=5.0e-3, gsw_abs=5.0e-2,
                 rswtoa_rel=5.0e-3, rswtoa_abs=5.0e-2),
    "fp64": dict(rth_abs=1.0e-9, rth_rel=1.0e-6, gsw_rel=1.0e-7, gsw_abs=1.0e-4,
                 rswtoa_rel=1.0e-7, rswtoa_abs=1.0e-4),
}


def _load(suite: Path, cid: int) -> dict:
    with open(suite / f"gsfcsw_case_{cid}.json", encoding="utf-8") as fh:
        return json.load(fh)


def _col(d, n):
    return np.asarray(d["columns"][n], dtype=np.float64)


def _run(d):
    one = jnp.ones((1,), dtype=jnp.float64)
    s = d["scalars"]
    column = GsfcSWColumnState(
        T=_col(d, "T")[None, :], p=_col(d, "P")[None, :], p8w=_col(d, "P8W")[None, :],
        qv=_col(d, "QV")[None, :], qc=_col(d, "QC")[None, :], qr=_col(d, "QR")[None, :],
        qi=_col(d, "QI")[None, :], qs=_col(d, "QS")[None, :], qg=_col(d, "QG")[None, :],
        dz=_col(d, "DZ")[None, :], cldfra=_col(d, "CLDFRA")[None, :],
        coszen=one * float(s["COSZEN"]), albedo=one * float(s["ALBEDO"]),
        solcon=one * float(s["SOLCON"]), julday=int(s["JULDAY"]),
        center_lat=float(s["CENTER_LAT"]), f_qi=True, warm_rain=False,
    )
    out = solve_gsfc_sw_column(column)
    rth = np.asarray(out.heating_rate)[0] / _col(d, "PI")
    return rth, float(np.asarray(out.gsw)[0]), float(np.asarray(out.rswtoa)[0])


def _check(d, tol):
    rth, gsw, rswtoa = _run(d)
    s = d["scalars"]
    oracle_rth = _col(d, "RTHRATEN")
    scale = max(float(np.max(np.abs(oracle_rth))), tol["rth_abs"])
    rth_abs = float(np.max(np.abs(rth - oracle_rth)))
    assert (rth_abs / scale <= tol["rth_rel"]) or (rth_abs <= tol["rth_abs"]), (
        f"RTHRATEN abs={rth_abs:.3e} rel={rth_abs/scale:.3e}")
    gsw_tol = max(tol["gsw_rel"] * abs(s["GSW"]), tol["gsw_abs"])
    assert abs(gsw - s["GSW"]) <= gsw_tol, f"GSW {gsw} vs {s['GSW']}"
    rswtoa_tol = max(tol["rswtoa_rel"] * abs(s["RSWTOA"]), tol["rswtoa_abs"])
    assert abs(rswtoa - s["RSWTOA"]) <= rswtoa_tol, f"RSWTOA {rswtoa} vs {s['RSWTOA']}"


@pytest.mark.parametrize("cid", CASES)
def test_gsfc_sw_fp64_precision_audit(cid: int) -> None:
    if not (SAVE_FP64 / f"gsfcsw_case_{cid}.json").exists():
        pytest.skip("fp64 GSFC savepoints not generated")
    _check(_load(SAVE_FP64, cid), TOL["fp64"])


@pytest.mark.parametrize("cid", CASES)
def test_gsfc_sw_fp32_canonical(cid: int) -> None:
    if not (SAVE_FP32 / f"gsfcsw_case_{cid}.json").exists():
        pytest.skip("fp32 GSFC savepoints not generated")
    _check(_load(SAVE_FP32, cid), TOL["fp32"])


def test_gsfc_sw_heating_nonnegative_and_finite() -> None:
    d = _load(SAVE_FP64, 1)
    rth, gsw, rswtoa = _run(d)
    assert np.all(np.isfinite(rth)) and np.isfinite(gsw) and np.isfinite(rswtoa)
    assert np.min(rth) >= -1.0e-12  # GSFCSWRAD clamps TTEN to >= 0


def test_gsfc_sw_night_is_zero() -> None:
    # case 3 is the night/zero-sun regime.
    d = _load(SAVE_FP64, 3)
    rth, gsw, rswtoa = _run(d)
    assert np.max(np.abs(rth)) == 0.0
    assert gsw == 0.0 and rswtoa == 0.0
