"""v0.6.0 Dudhia shortwave (ra_sw_physics=1) savepoint parity.

Validates the JAX Dudhia SW port against the unmodified WRF module_ra_sw.F
oracle savepoints generated by proofs/v060/oracle/dudhia_build_and_run.sh.
The fp64 oracle build must match to machine precision; the canonical fp32
build is bounded by the predeclared parity tolerances.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

import pytest

os.environ.setdefault("JAX_PLATFORM_NAME", "cpu")
os.environ.setdefault("JAX_PLATFORMS", "cpu")

import jax  # noqa: E402

jax.config.update("jax_enable_x64", True)
import jax.numpy as jnp  # noqa: E402
import numpy as np  # noqa: E402

from gpuwrf.physics.ra_sw_dudhia import DudhiaSWColumnState, solve_dudhia_sw_column  # noqa: E402


ROOT = Path(__file__).resolve().parents[1]
SAVE_FP32 = ROOT / "proofs" / "v060" / "savepoints"
SAVE_FP64 = ROOT / "proofs" / "v060" / "savepoints_fp64"
CASES = (1, 2, 3, 4, 5, 6, 7)

# Predeclared tolerances (mirror proofs/v060/run_dudhia_parity.py).
RTH_ABS = 5.0e-9
RTH_REL = 5.0e-4
GSW_REL = 5.0e-4
GSW_ABS = 5.0e-3
# fp64 oracle must reproduce the unmodified WRF fp64 build to machine precision.
RTH_REL_FP64 = 1.0e-11
GSW_ABS_FP64 = 1.0e-9


def _load(save_dir: Path, cid: int) -> dict:
    with open(save_dir / f"dudhia_case_{cid}.json", encoding="utf-8") as fh:
        return json.load(fh)


def _run_jax(d: dict) -> tuple[np.ndarray, float]:
    def c(name):
        return jnp.asarray(np.asarray(d["columns"][name], dtype=np.float64)[None, :])

    state = DudhiaSWColumnState(
        T=c("T"), p=c("P"), qv=c("QV"), qc=c("QC"), qr=c("QR"),
        qi=c("QI"), qs=c("QS"), qg=c("QG"), dz=c("DZ"),
        coszen=jnp.asarray([float(d["scalars"]["COSZEN"])]),
        albedo=jnp.asarray([float(d["scalars"]["ALBEDO"])]),
        solcon=jnp.asarray([float(d["scalars"]["SOLCON"])]),
        icloud=int(d["scalars"]["ICLOUD"]),
    )
    out = solve_dudhia_sw_column(state)
    pi = np.asarray(d["columns"]["PI"], dtype=np.float64)
    rthraten = np.asarray(out.heating_rate)[0] / pi
    return rthraten, float(np.asarray(out.gsw)[0])


@pytest.mark.parametrize("cid", CASES)
def test_dudhia_sw_fp32_parity(cid: int) -> None:
    d = _load(SAVE_FP32, cid)
    jax_rth, jax_gsw = _run_jax(d)
    oracle_rth = np.asarray(d["columns"]["RTHRATEN"], dtype=np.float64)
    oracle_gsw = float(d["scalars"]["GSW"])

    scale = max(float(np.max(np.abs(oracle_rth))), RTH_ABS)
    max_abs = float(np.max(np.abs(jax_rth - oracle_rth)))
    assert (max_abs / scale <= RTH_REL) or (max_abs <= RTH_ABS), (
        f"case {cid} RTHRATEN max_abs={max_abs:.3e} rel={max_abs/scale:.3e}"
    )
    gsw_tol = max(GSW_REL * abs(oracle_gsw), GSW_ABS)
    assert abs(jax_gsw - oracle_gsw) <= gsw_tol, (
        f"case {cid} GSW jax={jax_gsw} oracle={oracle_gsw}"
    )


@pytest.mark.parametrize("cid", CASES)
def test_dudhia_sw_fp64_machine_precision(cid: int) -> None:
    d = _load(SAVE_FP64, cid)
    jax_rth, jax_gsw = _run_jax(d)
    oracle_rth = np.asarray(d["columns"]["RTHRATEN"], dtype=np.float64)
    oracle_gsw = float(d["scalars"]["GSW"])

    scale = max(float(np.max(np.abs(oracle_rth))), 1.0e-30)
    max_abs = float(np.max(np.abs(jax_rth - oracle_rth)))
    assert max_abs / scale <= RTH_REL_FP64, (
        f"case {cid} fp64 RTHRATEN rel={max_abs/scale:.3e}"
    )
    assert abs(jax_gsw - oracle_gsw) <= max(GSW_ABS_FP64, 1e-9 * abs(oracle_gsw)), (
        f"case {cid} fp64 GSW err={abs(jax_gsw-oracle_gsw):.3e}"
    )


def test_dudhia_night_is_zero() -> None:
    # Case 3 is the zero-coszen night column: GSW and RTHRATEN must be exactly 0.
    d = _load(SAVE_FP64, 3)
    jax_rth, jax_gsw = _run_jax(d)
    assert jax_gsw == 0.0
    assert float(np.max(np.abs(jax_rth))) == 0.0
