"""v0.17 Held-Suarez idealized radiation (ra_lw_physics=31) savepoint parity.

Validates the JAX Held-Suarez port (gpuwrf.physics.ra_lw_hs) against the
unmodified WRF phys/module_ra_hs.F:HSRAD oracle savepoints generated by
proofs/v017/oracle/hs_build_and_run.sh. The fp64 oracle build must match to
machine precision; the canonical fp32 build is bounded by the predeclared
parity tolerances.

This is a real WRF-module oracle (HSRAD driven on prescribed soundings), not a
JAX self-compare. Held-Suarez carries no prognostic state, so this single-column
oracle fully exercises the scheme's column kernel.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

import pytest

os.environ.setdefault("JAX_PLATFORM_NAME", "cpu")
os.environ.setdefault("JAX_PLATFORMS", "cpu")

import jax  # noqa: E402

jax.config.update("jax_enable_x64", True)
import jax.numpy as jnp  # noqa: E402
import numpy as np  # noqa: E402

from gpuwrf.physics.ra_lw_hs import (  # noqa: E402
    HeldSuarezColumnState,
    solve_held_suarez_column,
)


ROOT = Path(__file__).resolve().parents[1]
SAVE_FP32 = ROOT / "proofs" / "v017" / "savepoints_hs"
SAVE_FP64 = ROOT / "proofs" / "v017" / "savepoints_hs_fp64"
CASES = (1, 2, 3, 4, 5, 6, 7)

# Predeclared tolerances. RTHRATEN here is the radiative theta tendency (K/s),
# O(1e-6); the relative bound is what binds, with a tiny absolute floor for the
# near-equilibrium layers where teq ~= T.
RTH_REL = 5.0e-4
RTH_ABS = 1.0e-12
# fp64 oracle must reproduce the unmodified WRF fp64 build to machine precision.
RTH_REL_FP64 = 1.0e-11
RTH_ABS_FP64 = 1.0e-18


def _load(save_dir: Path, cid: int) -> dict:
    with open(save_dir / f"hs_case_{cid}.json", encoding="utf-8") as fh:
        return json.load(fh)


def _run_jax(d: dict) -> np.ndarray:
    """Return the JAX Held-Suarez RTHRATEN (theta tendency, K/s) for the column."""

    def c(name):
        return jnp.asarray(np.asarray(d["columns"][name], dtype=np.float64)[None, :])

    p8w = np.asarray(d["columns"]["P8W"], dtype=np.float64)
    state = HeldSuarezColumnState(
        T=c("T"),
        p=c("P"),
        psfc=jnp.asarray([float(p8w[0])]),   # p8w(i,1,j) = lowest interface
        lat_deg=jnp.asarray([float(d["scalars"]["XLAT"])]),
    )
    out = solve_held_suarez_column(state)
    # Kernel returns dT/dt (K/s); WRF accumulates RTHRATEN += t_tend/pi.
    pi = np.asarray(d["columns"]["PI"], dtype=np.float64)
    rthraten = np.asarray(out.heating_rate)[0] / pi
    return rthraten


@pytest.mark.parametrize("cid", CASES)
def test_hs_fp32_parity(cid: int) -> None:
    d = _load(SAVE_FP32, cid)
    jax_rth = _run_jax(d)
    oracle_rth = np.asarray(d["columns"]["RTHRATEN"], dtype=np.float64)

    scale = max(float(np.max(np.abs(oracle_rth))), RTH_ABS)
    max_abs = float(np.max(np.abs(jax_rth - oracle_rth)))
    assert (max_abs / scale <= RTH_REL) or (max_abs <= RTH_ABS), (
        f"case {cid} ({d['scalars']['REGIME']}) RTHRATEN "
        f"max_abs={max_abs:.3e} rel={max_abs/scale:.3e}"
    )


@pytest.mark.parametrize("cid", CASES)
def test_hs_fp64_machine_precision(cid: int) -> None:
    d = _load(SAVE_FP64, cid)
    jax_rth = _run_jax(d)
    oracle_rth = np.asarray(d["columns"]["RTHRATEN"], dtype=np.float64)

    scale = max(float(np.max(np.abs(oracle_rth))), 1.0e-30)
    max_abs = float(np.max(np.abs(jax_rth - oracle_rth)))
    assert (max_abs / scale <= RTH_REL_FP64) or (max_abs <= RTH_ABS_FP64), (
        f"case {cid} ({d['scalars']['REGIME']}) fp64 RTHRATEN "
        f"rel={max_abs/scale:.3e} abs={max_abs:.3e}"
    )


def test_hs_signs_and_structure() -> None:
    """Sanity: relaxation drives T toward teq, and the forcing is non-zero.

    The deep-tropics/equator warm columns are warmer than the HS equilibrium in
    the lower troposphere, so the radiative tendency must be a net cooling there.
    """
    d = _load(SAVE_FP64, 1)  # equator_warm
    jax_rth = _run_jax(d)
    # Some layers must have an appreciable (non-degenerate) relaxation tendency.
    assert float(np.max(np.abs(jax_rth))) > 1.0e-7
