"""Generate src/gpuwrf/io/wrf_registry_defaults.py from the pristine WRF Registry.

usage: python gen_registry_defaults.py <WRF/Registry dir> <out.py>
Walks Registry.EM and its `include` lines (the em_real build), keeps every
``rconfig`` entry of the namelist groups &physics, &dynamics and &noah_mp, and
writes key -> (group, entries, type, default) with the default parsed to a
Python value.  The output is committed so the port needs no WRF tree at run
time; tests/test_namelist_binding.py re-runs this against data/wrf_pristine
when it exists and asserts byte identity.
"""
import re
import sys
from pathlib import Path

GROUPS = ("physics", "dynamics", "noah_mp")


def walk(path: Path, seen: set) -> list[str]:
    if path in seen or not path.is_file():
        return []
    seen.add(path)
    lines = []
    for line in path.read_text(errors="replace").splitlines():
        m = re.match(r"^\s*include\s+(\S+)", line)
        if m:
            lines += walk(path.parent / m.group(1), seen)
        else:
            lines.append(line)
    return lines


def parse_default(typ: str, raw: str):
    raw = raw.strip()
    if typ == "integer":
        return int(raw)
    if typ == "real":
        return float(raw.lower().replace("d", "e"))
    if typ == "logical":
        return raw.lower().strip(".") in ("true", "t")
    return raw.strip('"')


def main(reg_dir: str, out: str) -> None:
    entries = {}
    for line in walk(Path(reg_dir) / "Registry.EM", set()):
        if not line.startswith("rconfig"):
            continue
        tok = line.split()
        typ, key, how, nent = tok[1].lower(), tok[2].lower(), tok[3].lower(), tok[4].lower()
        m = re.fullmatch(r"namelist,(\w+)", how)
        if not m or m.group(1) not in GROUPS:
            continue
        if typ == "character":
            dm = re.search(r'"([^"]*)"', line.split(None, 5)[5])
            default = dm.group(1) if dm else ""
        else:
            default = parse_default(typ, tok[5])
        if key in entries:
            continue  # first definition wins (WRF registry semantics)
        entries[key] = (m.group(1), nent, typ, default)
    body = ",\n".join(f"    {k!r}: {v!r}" for k, v in sorted(entries.items()))
    Path(out).write_text(
        '"""WRF v4 Registry defaults of the &physics/&dynamics/&noah_mp namelist keys.\n\n'
        "GENERATED by proofs/o1_nlbind/gen_registry_defaults.py from the pristine WRF\n"
        "Registry (Registry.EM + includes, em_real build).  Do not edit by hand.\n"
        "key -> (group, entries, type, default); entries is '1' or 'max_domains' (or\n"
        'another Registry dimension name)."""\n\n'
        "WRF_REGISTRY_DEFAULTS = {\n" + body + ",\n}\n"
    )
    print(len(entries), "keys")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
