"""JIT/vmap-traceable GBM PBL column kernel (``bl_pbl_physics=12``).

This is a direct JAX transcription of the single-column path of pristine WRF
``phys/module_bl_gbmpbl.F`` (``GBMPBL`` -> ``GBM2D``): the moist
Grenier-Bretherton-McCaa prognostic-TKE PBL.  Inputs are bottom-up WRF
mass-level columns; the internal work arrays mirror the Fortran's top-down
storage (Fortran level 1 = model top, level ``kte`` = lowest mass level).

The wrapper preserves WRF's two-pass GBMPBL behavior: the internal GBM2D column
is called twice, TKE from pass 1 is retained, U/V tendencies are averaged across
passes, and scalar tendencies come from pass 2.  Validation is gated by
``proofs/v018/run_gbm_pbl12_parity.py`` against fp64 savepoints generated by a
standalone Fortran driver linked to the unmodified WRF module.
"""

from __future__ import annotations

from gpuwrf._x64_config import configure_jax_x64

import jax
from jax import config
import jax.numpy as jnp

configure_jax_x64()

G = 9.81
R_D = 287.0
CP = 7.0 * R_D / 2.0
R_V = 461.6
XLV = 2.5e6
ROVCP = R_D / CP
EP1 = R_V / R_D - 1.0
EP2 = R_D / R_V
KARMAN = 0.4
P1000 = 1.0e5
SVP1 = 0.6112
SVP2 = 17.67
SVP3 = 29.65
SVPT0 = 273.15

XFR = 0.1
AONE = 1.9 * XFR
ATWO = 10.0
CFAC = 7.8
CZERO = 5.869
RSTBL = 1.5
VK = 0.4
PREF = 100000.0
NUK = 5.0
KMAX = 1000.0
N2MIN = 1.0e-7


def _tridag(a: jax.Array, b: jax.Array, c: jax.Array, r: jax.Array) -> jax.Array:
    """Numerical-Recipes tridiagonal solve matching WRF ``tridag``."""

    n = r.shape[0]
    bet0 = 1.0 / b[0]
    u0 = r[0] * bet0

    def fwd(carry, j):
        bet_prev, u_prev = carry
        gam_j = c[j - 1] * bet_prev
        bet_j = 1.0 / (b[j] - a[j] * gam_j)
        u_j = (r[j] - a[j] * u_prev) * bet_j
        return (bet_j, u_j), (gam_j, u_j)

    (_, _), (gam_tail, u_tail) = jax.lax.scan(
        fwd, (bet0, u0), jnp.arange(1, n, dtype=jnp.int32)
    )
    gam = jnp.concatenate([jnp.zeros(1, dtype=r.dtype), gam_tail])
    u_fwd = jnp.concatenate([u0[None], u_tail])

    def bwd(u_next, j):
        k = n - 2 - j
        u_k = u_fwd[k] - gam[k + 1] * u_next
        return u_k, u_k

    _, u_rev = jax.lax.scan(bwd, u_fwd[n - 1], jnp.arange(n - 1, dtype=jnp.int32))
    return jnp.concatenate([u_rev[::-1], u_fwd[n - 1 : n]])


def _sat_mr(temp: jax.Array, pressure_pa: jax.Array) -> jax.Array:
    svp1pa = SVP1 * 10.0
    evs = 100.0 * svp1pa * jnp.exp(SVP2 * (temp - SVPT0) / (temp - SVP3))
    return EP2 / (pressure_pa / evs - 1.0)


def _n2(thlx: jax.Array, exnerfl: jax.Array, epop: jax.Array, qwx: jax.Array,
        rdza: jax.Array, rexnerfl: jax.Array) -> tuple[jax.Array, jax.Array]:
    """WRF ``n2`` buoyancy-jump routine.

    ``thlx``/``qwx`` are top-down half-level arrays of length ``n``. Flux-level
    outputs have length ``n+1``; indices ``1..n-1`` are interior, ``n`` is filled
    by the caller with the surface jump.
    """

    n = thlx.shape[0]
    ns = jnp.zeros(n + 1, dtype=thlx.dtype)
    rcldb = jnp.zeros(n + 1, dtype=thlx.dtype)
    cpoxlv = CP / XLV
    xlvocp = XLV / CP

    def body(k, carry):
        ns, rcldb = carry
        templ_b = thlx[k] * exnerfl[k]
        rvls_b = 100.0 * SVP1 * 10.0 * jnp.exp(
            SVP2 * (templ_b - SVPT0) / (templ_b - SVP3)
        ) * epop[k]
        temps_b = templ_b + (qwx[k] - rvls_b) / (
            cpoxlv + EP2 * XLV * rvls_b / (R_D * templ_b * templ_b)
        )
        rvls_b = 100.0 * SVP1 * 10.0 * jnp.exp(
            SVP2 * (temps_b - SVPT0) / (temps_b - SVP3)
        ) * epop[k]
        rcld_b = jnp.maximum(qwx[k] - rvls_b, 0.0)
        tempv_b = (templ_b + xlvocp * rcld_b) * (
            1.0 + EP1 * (qwx[k] - rcld_b) - rcld_b
        )
        tvbl = tempv_b * rexnerfl[k]

        templ_a = thlx[k - 1] * exnerfl[k]
        rvls_a = 100.0 * SVP1 * 10.0 * jnp.exp(
            SVP2 * (templ_a - SVPT0) / (templ_a - SVP3)
        ) * epop[k]
        temps_a = templ_a + (qwx[k - 1] - rvls_a) / (
            cpoxlv + EP2 * XLV * rvls_a / (R_D * templ_a * templ_a)
        )
        rvls_a = 100.0 * SVP1 * 10.0 * jnp.exp(
            SVP2 * (temps_a - SVPT0) / (temps_a - SVP3)
        ) * epop[k]
        rcld_a = jnp.maximum(qwx[k - 1] - rvls_a, 0.0)
        tempv_a = (templ_a + xlvocp * rcld_a) * (
            1.0 + EP1 * (qwx[k - 1] - rcld_a) - rcld_a
        )
        tvab = tempv_a * rexnerfl[k]

        thvxfl = 0.5 * (tvab + tvbl)
        dtvdz = (tvab - tvbl) * rdza[k]
        ns = ns.at[k].set(G / thvxfl * dtvdz)
        rcldb = rcldb.at[k].set(rcld_b)
        return ns, rcldb

    ns, rcldb = jax.lax.fori_loop(1, n, body, (ns, rcldb))
    ns = ns.at[0].set(ns[1])
    return ns, rcldb


def _pblhgt_simple(zq: jax.Array, nsquar: jax.Array, tke: jax.Array) -> tuple[jax.Array, jax.Array, jax.Array, jax.Array, jax.Array]:
    """Bottom-connected GBM PBL-height/mixing-length path.

    The staged WRF GBM oracle exercises either a bottom-connected unstable layer
    or the stable first-interface fallback.  This routine keeps that path
    traceable and records the convective-layer top for the MY diffusivity special
    case.
    """

    n = tke.shape[0] - 1
    kidx = jnp.arange(n + 1, dtype=jnp.int32)
    stable = nsquar > 0.0
    b_stable = jnp.minimum(RSTBL * jnp.sqrt(jnp.maximum(tke, 0.0) / jnp.maximum(nsquar, 1.0e-30)),
                           KARMAN * zq[: n + 1])
    bbls = jnp.where(stable, b_stable, 0.0)
    conv = nsquar <= 0.0
    connected = jnp.cumprod(conv[1 : n + 1][::-1].astype(jnp.int32))[::-1].astype(bool)
    has_surface_layer = conv[n]
    any_connected = jnp.any(connected)
    top_k = jnp.argmax(connected).astype(jnp.int32) + 1
    top_k = jnp.where(jnp.logical_and(has_surface_layer, any_connected), top_k, n)
    pbl_index = jnp.minimum(jnp.maximum(top_k - 1, 0), n - 1)
    pblx = zq[pbl_index]
    kpbl = (n - pbl_index).astype(jnp.int32)
    blinf = XFR * (zq[jnp.maximum(pbl_index - 1, 0)] - zq[n + 1])
    in_bottom_layer = jnp.logical_and(kidx >= pbl_index, has_surface_layer)
    b_conv = jnp.minimum(KARMAN * zq[: n + 1], blinf)
    bbls = jnp.where(in_bottom_layer, b_conv, bbls)
    iconv = has_surface_layer.astype(jnp.int32)
    return bbls, pblx, pbl_index, iconv, kpbl


def _my(bbls: jax.Array, nsquar: jax.Array, tke: jax.Array, top_k: jax.Array,
        iconv: jax.Array, thlx: jax.Array, thx: jax.Array, qwx: jax.Array,
        rcldb: jax.Array, rexnerhl: jax.Array) -> tuple[jax.Array, jax.Array, jax.Array]:
    n = thlx.shape[0]
    sm = jnp.ones(n + 1, dtype=thlx.dtype)
    sh = jnp.ones(n + 1, dtype=thlx.dtype)
    kzm = jnp.zeros(n + 1, dtype=thlx.dtype)
    kth = jnp.zeros(n + 1, dtype=thlx.dtype)
    kethl = jnp.zeros(n, dtype=thlx.dtype)
    a1 = 0.92
    b1 = 16.6
    c1 = 0.08
    a2 = 0.74
    b2 = 10.1
    a1ob1 = a1 / b1

    def body(j, carry):
        sm, sh, kzm, kth, kethl = carry
        k = n - 1 - j  # k = n-1 .. 1, matching Fortran K=kte..2
        gh = -bbls[k] * bbls[k] * nsquar[k] / (2.0 * tke[k] + 1.0e-9)
        gh = jnp.clip(gh, -0.28, 0.0233)
        sm_k = a1 * (
            1.0 - 3.0 * c1 - 6.0 * a1ob1
            - 3.0 * a2 * gh * ((b2 - 3.0 * a2) * (1.0 - 6.0 * a1ob1) - 3.0 * c1 * (b2 + 6.0 * a1))
        ) / ((1.0 - 3.0 * a2 * gh * (6.0 * a1 + b2)) * (1.0 - 9.0 * a1 * a2 * gh))
        sh_k = a2 * (1.0 - 6.0 * a1ob1) / (1.0 - 3.0 * a2 * gh * (6.0 * a1 + b2))
        q = jnp.sqrt(jnp.maximum(2.0 * tke[k], 0.0))
        kzm_k = jnp.minimum(bbls[k] * q * sm_k, KMAX)
        kth_k = jnp.minimum(bbls[k] * q * sh_k, KMAX)
        kethl_k = jnp.minimum(NUK * jnp.sqrt(jnp.maximum(kzm_k * kzm[k + 1], 0.0)), KMAX)
        sm = sm.at[k].set(sm_k)
        sh = sh.at[k].set(sh_k)
        kzm = kzm.at[k].set(kzm_k)
        kth = kth.at[k].set(kth_k)
        kethl = kethl.at[k].set(kethl_k)
        return sm, sh, kzm, kth, kethl

    sm, sh, kzm, kth, kethl = jax.lax.fori_loop(0, n - 1, body, (sm, sh, kzm, kth, kethl))

    k = top_k
    active_top = jnp.logical_and(iconv > 0, jnp.logical_and(k < n, nsquar[k] >= N2MIN))
    delthvl = (
        thlx[jnp.maximum(k - 2, 0)] + thx[jnp.maximum(k - 2, 0)] * EP1 * qwx[jnp.maximum(k - 2, 0)]
        - (thlx[k] + thx[k] * EP1 * qwx[k])
    )
    elambda = (XLV / CP) * rcldb[k] * rexnerhl[k] / jnp.maximum(delthvl, 0.1)
    biga = AONE * (1.0 + ATWO * 0.8 * elambda)
    kth_top = jnp.minimum(kth[k], biga * jnp.sqrt(jnp.maximum(tke[k], 0.0) ** 3) / nsquar[k] / jnp.maximum(bbls[k], bbls[k + 1]))
    kzm_top = jnp.minimum(kzm[k], kth_top / sh[k + 1] * sm[k + 1])
    kethl = kethl.at[k].set(jnp.where(active_top, NUK * kzm[k + 1], kethl[k]))
    kethl = kethl.at[jnp.maximum(k - 1, 0)].set(jnp.where(jnp.logical_and(active_top, k >= 2), 0.0, kethl[jnp.maximum(k - 1, 0)]))
    kth = kth.at[k].set(jnp.where(active_top, kth_top, kth[k]))
    kzm = kzm.at[k].set(jnp.where(active_top, kzm_top, kzm[k]))

    kethl = kethl.at[0].set(kethl[1])
    kethl = kethl.at[n - 1].set(NUK * 0.5 * kzm[n - 1])
    return kzm, kth, kethl


def _scalar_update(thlx: jax.Array, qwx: jax.Array, qcx: jax.Array, exnerhl: jax.Array,
                   preshl: jax.Array) -> tuple[jax.Array, jax.Array, jax.Array]:
    n = thlx.shape[0]
    xlvocp = XLV / CP

    def body(k, carry):
        thx, qx, qcx_new = carry
        templ = thlx[k] * exnerhl[k]
        temps = templ
        rvls = _sat_mr(temps, preshl[k])

        def iter_body(_, vals):
            temps_i, rvls_i = vals
            temps_i = temps_i + ((templ - temps_i) * CP / XLV + qwx[k] - rvls_i) / (
                CP / XLV + EP2 * XLV * rvls_i / R_D / (temps_i * temps_i)
            )
            rvls_i = _sat_mr(temps_i, preshl[k])
            return temps_i, rvls_i

        temps, rvls = jax.lax.fori_loop(0, 3, iter_body, (temps, rvls))
        qcx_k = jnp.maximum(qwx[k] - rvls, 0.0)
        qx_k = qwx[k] - qcx_k
        thx_k = (templ + qcx_k * xlvocp) / exnerhl[k]
        thx = thx.at[k].set(thx_k)
        qx = qx.at[k].set(qx_k)
        qcx_new = qcx_new.at[k].set(qcx_k)
        return thx, qx, qcx_new

    return jax.lax.fori_loop(0, n, body, (jnp.zeros_like(thlx), jnp.zeros_like(qwx), jnp.zeros_like(qcx)))


def _gbm2d(u: jax.Array, v: jax.Array, t: jax.Array, qv: jax.Array, qc: jax.Array,
           p: jax.Array, pii: jax.Array, dz: jax.Array, tke_in: jax.Array, *,
           psfc: jax.Array, znt: jax.Array, ust: jax.Array, hfx: jax.Array,
           qfx: jax.Array, tsk: jax.Array, gz1oz0: jax.Array, wspd: jax.Array,
           br: jax.Array, psim: jax.Array, psih: jax.Array, dt: float,
           xland: jax.Array) -> dict[str, jax.Array]:
    del znt, ust, br, psih
    n = u.shape[0]
    rdt = 1.0 / dt
    dt2 = dt
    r1cp = 1.0 / CP
    xlvocp = XLV / CP

    ux = u[::-1]
    vx = v[::-1]
    tx = t[::-1]
    qx = qv[::-1]
    qcx = qc[::-1]
    preshl = p[::-1]
    exnerhl = (preshl / PREF) ** ROVCP
    rexnerhl = 1.0 / exnerhl

    zq = jnp.zeros(n + 2, dtype=u.dtype)

    def zq_body(j, zq):
        k = n - 1 - j
        return zq.at[k].set(zq[k + 1] + dz[n - 1 - k])

    zq = jax.lax.fori_loop(0, n, zq_body, zq)
    za = 0.5 * (zq[:n] + zq[1 : n + 1])
    dzq = zq[:n] - zq[1 : n + 1]
    rdzq = 1.0 / dzq

    thx = tx * rexnerhl
    qwx = qx + qcx
    tvcon = 1.0 + EP1 * qx - qcx
    tvx = tx * tvcon
    thvx = thx * tvcon
    thlx = thx - xlvocp * rexnerhl * qcx
    uxs = ux
    vxs = vx
    thxs = thx
    qxs = qx
    qcxs = qcx
    rhoxhl = preshl / (R_D * tvx)
    rrhoxhl = 1.0 / rhoxhl

    presfl = jnp.zeros(n + 1, dtype=u.dtype)
    exnerfl = jnp.ones(n + 1, dtype=u.dtype)
    rexnerfl = jnp.ones(n + 1, dtype=u.dtype)
    epop = jnp.zeros(n + 1, dtype=u.dtype)
    rdza = jnp.zeros(n + 1, dtype=u.dtype)
    dza = jnp.zeros(n + 1, dtype=u.dtype)
    rhoxfl = jnp.zeros(n + 1, dtype=u.dtype)
    rrhoxfl = jnp.zeros(n + 1, dtype=u.dtype)
    svs = jnp.zeros(n + 1, dtype=u.dtype)
    dqwdz = jnp.zeros(n + 1, dtype=u.dtype)
    dtldz = jnp.zeros(n + 1, dtype=u.dtype)

    def flux_body(k, carry):
        presfl, exnerfl, rexnerfl, epop, dza, rdza, rhoxfl, rrhoxfl, svs, dqwdz, dtldz = carry
        pfl = jnp.exp(0.5 * (jnp.log(preshl[k - 1]) + jnp.log(preshl[k])))
        dzak = za[k - 1] - za[k]
        rdzak = 1.0 / dzak
        exk = (pfl / PREF) ** ROVCP
        rexk = 1.0 / exk
        fracz = (zq[k] - za[k]) * rdzak
        rhof = rhoxhl[k] + (rhoxhl[k - 1] - rhoxhl[k]) * fracz
        dudz = (ux[k - 1] - ux[k]) * rdzak
        dvdz = (vx[k - 1] - vx[k]) * rdzak
        presfl = presfl.at[k].set(pfl)
        epop = epop.at[k].set(EP2 / pfl)
        dza = dza.at[k].set(dzak)
        rdza = rdza.at[k].set(rdzak)
        exnerfl = exnerfl.at[k].set(exk)
        rexnerfl = rexnerfl.at[k].set(rexk)
        rhoxfl = rhoxfl.at[k].set(rhof)
        rrhoxfl = rrhoxfl.at[k].set(1.0 / rhof)
        svs = svs.at[k].set(dudz * dudz + dvdz * dvdz)
        dqwdz = dqwdz.at[k].set((qwx[k - 1] - qwx[k]) * rdzak)
        dtldz = dtldz.at[k].set((thlx[k - 1] - thlx[k]) * rdzak)
        return presfl, exnerfl, rexnerfl, epop, dza, rdza, rhoxfl, rrhoxfl, svs, dqwdz, dtldz

    presfl, exnerfl, rexnerfl, epop, dza, rdza, rhoxfl, rrhoxfl, svs, dqwdz, dtldz = jax.lax.fori_loop(
        1, n, flux_body,
        (presfl, exnerfl, rexnerfl, epop, dza, rdza, rhoxfl, rrhoxfl, svs, dqwdz, dtldz),
    )
    presfl = presfl.at[n].set(psfc)
    rexnerfl = rexnerfl.at[n].set((PREF / psfc) ** ROVCP)
    exnerfl = exnerfl.at[n].set(1.0 / rexnerfl[n])
    q0s = _sat_mr(tsk, psfc)
    thgb = tsk * rexnerfl[n]
    rhoxsf = psfc / (R_D * tvx[n - 1])
    wspd1 = jnp.sqrt(ux[n - 1] * ux[n - 1] + vx[n - 1] * vx[n - 1]) + 1.0e-4
    thv0 = thgb * (1.0 + EP1 * q0s)
    dthv = thvx[n - 1] - thv0
    ustx0 = wspd1 * VK / (gz1oz0 - psim)
    ustx = jnp.where((xland - 1.5) < 0.0, jnp.maximum(ustx0, 0.1), ustx0)

    tke = jnp.concatenate([tke_in[::-1], jnp.zeros(1, dtype=u.dtype)])
    nsquar, rcldb = _n2(thlx, exnerfl, epop, qwx, rdza, rexnerfl)
    nsquar = nsquar.at[n].set(G / thvx[n - 1] * dthv / za[n - 1])
    bbls, pblx, top_k, iconv, kpbl = _pblhgt_simple(zq, nsquar, tke)

    def scalar_pass(_, carry):
        nsquar, rcldb, kzm, kth, kethl, uimp1, uimp2 = carry
        kzm, kth, kethl = _my(bbls, nsquar, tke, top_k, iconv, thlx, thx, qwx, rcldb, rexnerhl)
        a = jnp.zeros(n, dtype=u.dtype)
        b = jnp.zeros(n, dtype=u.dtype)
        c = jnp.zeros(n, dtype=u.dtype)
        r1 = jnp.zeros(n, dtype=u.dtype)
        r2 = jnp.zeros(n, dtype=u.dtype)

        def coeff_body(k, vals):
            a, b, c, r1, r2 = vals
            a_k = jnp.where(k == 0, 0.0, -(rhoxfl[k] * rrhoxhl[k]) * kth[k] * dt2 * rdzq[k] * rdza[k])
            c_k = jnp.where(k == n - 1, 0.0, -(rhoxfl[k + 1] * rrhoxhl[k]) * kth[k + 1] * dt2 * rdzq[k] * rdza[k + 1])
            b_k = 1.0 - a_k - c_k
            surface = k == n - 1
            r2_k = jnp.where(surface, qwx[k] + dt2 * qfx * rrhoxhl[k] * rdzq[n - 1], qwx[k])
            r1_k = jnp.where(
                surface,
                thlx[k] + dt2 * hfx * rrhoxhl[k] * r1cp * rdzq[n - 1] * rexnerhl[n - 1],
                thlx[k],
            )
            return a.at[k].set(a_k), b.at[k].set(b_k), c.at[k].set(c_k), r1.at[k].set(r1_k), r2.at[k].set(r2_k)

        a, b, c, r1, r2 = jax.lax.fori_loop(0, n, coeff_body, (a, b, c, r1, r2))
        uimp1 = _tridag(a, b, c, r1)
        uimp2 = _tridag(a, b, c, r2)
        nsquar, rcldb = _n2(uimp1, exnerfl, epop, uimp2, rdza, rexnerfl)
        thx_t = uimp1[n - 1] + xlvocp * rexnerhl[n - 1] * qcx[n - 1]
        thvx_t = thx_t * tvcon[n - 1]
        dthv_t = thvx_t - thv0
        nsquar = nsquar.at[n].set(G / thvx_t * dthv_t / za[n - 1])
        return nsquar, rcldb, kzm, kth, kethl, uimp1, uimp2

    zvec = jnp.zeros(n, dtype=u.dtype)
    nsquar, rcldb, kzm, kth, kethl, uimp1, uimp2 = jax.lax.fori_loop(
        0, 2, scalar_pass,
        (nsquar, rcldb, jnp.zeros(n + 1, dtype=u.dtype), jnp.zeros(n + 1, dtype=u.dtype),
         jnp.zeros(n, dtype=u.dtype), zvec, zvec),
    )
    thlx = uimp1
    qwx = uimp2
    thx, qx, qcx = _scalar_update(thlx, qwx, qcx, exnerhl, preshl)
    thvx = thx * (1.0 + EP1 * qx - qcx)

    # Momentum diffusion.
    a = jnp.zeros(n, dtype=u.dtype)
    b = jnp.zeros(n, dtype=u.dtype)
    c = jnp.zeros(n, dtype=u.dtype)
    r1 = jnp.zeros(n, dtype=u.dtype)
    r2 = jnp.zeros(n, dtype=u.dtype)

    def mom_body(k, vals):
        a, b, c, r1, r2 = vals
        a_k = jnp.where(k == 0, 0.0, -(rhoxfl[k] * rrhoxhl[k]) * kzm[k] * dt2 * rdzq[k] * rdza[k])
        c_k = jnp.where(k == n - 1, 0.0, -(rhoxfl[k + 1] * rrhoxhl[k]) * kzm[k + 1] * dt2 * rdzq[k] * rdza[k + 1])
        b_k = 1.0 - a_k - c_k
        uflxp = -ustx * ustx * ux[n - 1] / wspd1
        vflxp = -ustx * ustx * vx[n - 1] / wspd1
        surface = k == n - 1
        r1_k = jnp.where(surface, ux[k] + dt2 * uflxp * (rhoxsf * rrhoxhl[k]) * rdzq[n - 1], ux[k])
        r2_k = jnp.where(surface, vx[k] + dt2 * vflxp * (rhoxsf * rrhoxhl[k]) * rdzq[n - 1], vx[k])
        return a.at[k].set(a_k), b.at[k].set(b_k), c.at[k].set(c_k), r1.at[k].set(r1_k), r2.at[k].set(r2_k)

    a, b, c, r1, r2 = jax.lax.fori_loop(0, n, mom_body, (a, b, c, r1, r2))
    u_new = _tridag(a, b, c, r1)
    v_new = _tridag(a, b, c, r2)
    ux = u_new
    vx = v_new

    def svs_body(k, svs):
        dudz = (ux[k - 1] - ux[k]) * rdza[k]
        dvdz = (vx[k - 1] - vx[k]) * rdza[k]
        return svs.at[k].set(dudz * dudz + dvdz * dvdz)

    svs = jax.lax.fori_loop(1, n, svs_body, svs)

    # Cloud ice is zero in the staged oracle; RQCBLTEN is diagnosed from qcx above.

    bouyan = jnp.zeros(n + 1, dtype=u.dtype)
    shear = jnp.zeros(n + 1, dtype=u.dtype)

    def prod_body(k, vals):
        bouyan, shear = vals
        return bouyan.at[k].set(-kth[k] * nsquar[k]), shear.at[k].set(kzm[k] * svs[k])

    bouyan, shear = jax.lax.fori_loop(1, n, prod_body, (bouyan, shear))
    ktop = top_k
    rad = jnp.where(
        jnp.logical_and(iconv > 0, jnp.logical_and(qcx[ktop] > 1.0e-8, ktop > 0)),
        0.0,  # RTHRATEN is zero in the staged/current operational path.
        0.0,
    )
    bouyan = bouyan.at[ktop].add(rad)

    tke = tke.at[0].set(0.0)
    bbls = bbls.at[0].set(0.0)
    tke = tke.at[n].set(3.25 * ustx * ustx)
    m = n - 1
    a = jnp.zeros(m, dtype=u.dtype)
    b = jnp.zeros(m, dtype=u.dtype)
    c = jnp.zeros(m, dtype=u.dtype)
    r1 = jnp.zeros(m, dtype=u.dtype)
    rczero = 1.0 / CZERO

    def tke_body(j, vals):
        a, b, c, r1 = vals
        k = j + 1  # top-down flux/full index for Fortran K=2..n
        a_k = jnp.where(k == 1, 0.0, -(rhoxhl[k - 1] * rrhoxfl[k]) * kethl[k - 1] * dt2 * rdzq[k - 1] * rdza[k])
        c_k = jnp.where(k == n - 1, 0.0, -(rhoxhl[k] * rrhoxfl[k]) * kethl[k] * dt2 * rdzq[k] * rdza[k])
        tbbls = jnp.maximum(bbls[k], bbls[jnp.minimum(k + 1, n)])
        interior_b = 1.0 - a_k - c_k + jnp.where(tbbls > 0.0, dt2 * jnp.sqrt(jnp.maximum(tke[k], 0.0)) * rczero / tbbls, 0.0)
        surface_b = 1.0 - a_k - c_k + jnp.where(
            bbls[k] > 0.0,
            dt2 * (jnp.sqrt(jnp.maximum(tke[k], 0.0)) * rczero / bbls[k]
                   + rhoxhl[k] * rrhoxfl[k] * kethl[k] * rdzq[k] * rdza[k]),
            dt2 * rhoxhl[k] * rrhoxfl[k] * kethl[k] * rdzq[k] * rdza[k],
        )
        b_k = jnp.where(k == n - 1, surface_b, interior_b)
        r_k = jnp.where(
            k == n - 1,
            tke[k] + dt2 * (shear[k] + bouyan[k] + tke[n] * (rhoxhl[k] * rrhoxfl[k]) * kethl[k] * rdzq[k] * rdza[k]),
            tke[k] + dt2 * (shear[k] + bouyan[k]),
        )
        return a.at[j].set(a_k), b.at[j].set(b_k), c.at[j].set(c_k), r1.at[j].set(r_k)

    a, b, c, r1 = jax.lax.fori_loop(0, m, tke_body, (a, b, c, r1))
    tke_sol = _tridag(a, b, c, r1)
    tke = tke.at[1:n].set(jnp.maximum(tke_sol, 0.001))

    rublten_td = (ux - uxs) * rdt
    rvblten_td = (vx - vxs) * rdt
    t2dten_td = (thx - thxs) * exnerhl * rdt
    rqvblten_td = (qx - qxs) * rdt
    rqcblten_td = (qcx - qcxs) * rdt

    return {
        "rublten": rublten_td[::-1],
        "rvblten": rvblten_td[::-1],
        "rthblten": t2dten_td[::-1] / pii,
        "rqvblten": rqvblten_td[::-1],
        "rqcblten": rqcblten_td[::-1],
        "tke": tke[:n][::-1],
        "kzm": kzm[:n][::-1],
        "kth": kth[:n][::-1],
        "kethl": kethl[::-1],
        "el": bbls[:n][::-1],
        "pblh": pblx,
        "kpbl": kpbl,
        "ust": ustx,
    }


def gbm_column(u: jax.Array, v: jax.Array, t: jax.Array, qv: jax.Array, qc: jax.Array,
               p: jax.Array, pii: jax.Array, dz: jax.Array, tke: jax.Array, *,
               psfc: jax.Array, znt: jax.Array, ust: jax.Array, hfx: jax.Array,
               qfx: jax.Array, tsk: jax.Array, gz1oz0: jax.Array, wspd: jax.Array,
               br: jax.Array, psim: jax.Array, psih: jax.Array, dt: float,
               xland: jax.Array) -> dict[str, jax.Array]:
    first = _gbm2d(
        u, v, t, qv, qc, p, pii, dz, tke,
        psfc=psfc, znt=znt, ust=ust, hfx=hfx, qfx=qfx, tsk=tsk,
        gz1oz0=gz1oz0, wspd=wspd, br=br, psim=psim, psih=psih, dt=dt, xland=xland,
    )
    second = _gbm2d(
        u, v, t, qv, qc, p, pii, dz, first["tke"],
        psfc=psfc, znt=znt, ust=first["ust"], hfx=hfx, qfx=qfx, tsk=tsk,
        gz1oz0=gz1oz0, wspd=wspd, br=br, psim=psim, psih=psih, dt=dt, xland=xland,
    )
    out = dict(second)
    out["rublten"] = 0.5 * (first["rublten"] + second["rublten"])
    out["rvblten"] = 0.5 * (first["rvblten"] + second["rvblten"])
    out["tke"] = first["tke"]
    return out


def gbm_columns(u, v, t, qv, qc, p, pii, dz, tke, *, psfc, znt, ust, hfx, qfx,
                tsk, gz1oz0, wspd, br, psim, psih, dt=60.0, xland):
    """Batched GBM PBL kernel over leading column axis."""

    def one(u_, v_, t_, qv_, qc_, p_, pii_, dz_, tke_,
            psfc_, znt_, ust_, hfx_, qfx_, tsk_, gz_, wspd_, br_, psim_, psih_, xland_):
        return gbm_column(
            u_, v_, t_, qv_, qc_, p_, pii_, dz_, tke_,
            psfc=psfc_, znt=znt_, ust=ust_, hfx=hfx_, qfx=qfx_, tsk=tsk_,
            gz1oz0=gz_, wspd=wspd_, br=br_, psim=psim_, psih=psih_,
            dt=dt, xland=xland_,
        )

    raw = jax.vmap(one)(
        u, v, t, qv, qc, p, pii, dz, tke,
        psfc, znt, ust, hfx, qfx, tsk, gz1oz0, wspd, br, psim, psih, xland,
    )
    return {
        "u": raw["rublten"],
        "v": raw["rvblten"],
        "theta": raw["rthblten"],
        "qv": raw["rqvblten"],
        "qc": raw["rqcblten"],
        "qke": raw["tke"],
        "tke": raw["tke"],
        "kzm": raw["kzm"],
        "kth": raw["kth"],
        "kethl": raw["kethl"],
        "el_pbl": raw["el"],
        "pblh": raw["pblh"],
        "kpbl": raw["kpbl"],
        "ust": raw["ust"],
    }


__all__ = ["gbm_column", "gbm_columns"]
