#!/usr/bin/env python3
"""v0.18 PBL12 GBM JAX-vs-WRF-savepoint parity proof.

The oracle is the fp64 savepoint set under ``proofs/v017/savepoints_fp64/gbm``,
generated by ``proofs/v017/oracle/gbm/build_and_run.sh`` from a standalone
Fortran driver linked against the unmodified pristine WRF ``module_bl_gbmpbl.F``.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Any

os.environ.setdefault("JAX_PLATFORM_NAME", "cpu")
os.environ.setdefault("JAX_PLATFORMS", "cpu")

import jax
import jax.numpy as jnp
import numpy as np

jax.config.update("jax_enable_x64", True)

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))

from gpuwrf.physics.bl_gbm import gbm_columns  # noqa: E402

SP = ROOT / "proofs" / "v017" / "savepoints_fp64" / "gbm"
REPORT = ROOT / "proofs" / "v018" / "gbm_pbl12_jax_parity.json"
CASES = (1, 2, 3, 4, 5, 6)

TEND_ABS_TOL = 5.0e-11
TEND_REL_TOL = 2.0e-8
TKE_ABS_TOL = 5.0e-10
TKE_REL_TOL = 2.0e-8
PBL_ABS_TOL = 1.0e-8
PBL_REL_TOL = 1.0e-10
REL_FLOOR = 1.0e-30

FIELDS = {
    "RUBLTEN": "u",
    "RVBLTEN": "v",
    "RTHBLTEN": "theta",
    "RQVBLTEN": "qv",
    "RQCBLTEN": "qc",
    "TKE_PBL": "tke",
}


def _load(case: int) -> dict[str, Any]:
    return json.loads((SP / f"gbm_case_{case}.json").read_text(encoding="utf-8"))


def _col(data: dict[str, Any], name: str) -> np.ndarray:
    return np.asarray(data["columns"][name], dtype=np.float64)


def _metric(actual, expected, *, abs_tol: float, rel_tol: float) -> dict[str, Any]:
    a = np.asarray(actual, dtype=np.float64).ravel()
    b = np.asarray(expected, dtype=np.float64).ravel()
    diff = np.abs(a - b)
    max_abs = float(np.max(diff))
    scale = max(float(np.max(np.abs(b))), REL_FLOOR)
    max_rel = max_abs / scale
    idx = int(np.argmax(diff))
    return {
        "candidate": float(a[idx]),
        "reference": float(b[idx]),
        "max_abs": max_abs,
        "max_rel": float(max_rel),
        "scale": scale,
        "max_abs_index": idx,
        "abs_tolerance": abs_tol,
        "rel_tolerance": rel_tol,
        "pass": bool(max_abs <= abs_tol or max_rel <= rel_tol),
    }


def _build_batch():
    profile_keys = ("U", "V", "T", "QV", "P", "PI", "DZ")
    scalar_keys = ("PSFC", "ZNT", "UST", "HFX", "QFX", "TSK", "GZ1OZ0",
                   "WSPD", "BR", "PSIM", "PSIH", "XLAND")
    profiles = {key: [] for key in profile_keys}
    scalars = {key: [] for key in scalar_keys}
    expected = []
    for case in CASES:
        data = _load(case)
        for key in profile_keys:
            profiles[key].append(_col(data, key))
        for key in scalar_keys:
            scalars[key].append(float(data["scalars"][key]))
        expected.append(data)

    arr = lambda values: jnp.asarray(np.stack(values), dtype=jnp.float64)  # noqa: E731
    scalar_arr = lambda values: jnp.asarray(np.asarray(values), dtype=jnp.float64)  # noqa: E731
    inputs = {
        "u": arr(profiles["U"]),
        "v": arr(profiles["V"]),
        "t": arr(profiles["T"]),
        "qv": arr(profiles["QV"]),
        "qc": jnp.zeros_like(arr(profiles["QV"])),
        "p": arr(profiles["P"]),
        "pii": arr(profiles["PI"]),
        "dz": arr(profiles["DZ"]),
        "tke": jnp.full_like(arr(profiles["QV"]), 0.001),
    }
    forcing = {key.lower(): scalar_arr(values) for key, values in scalars.items()}
    return inputs, forcing, expected


def _git_head() -> str:
    return subprocess.check_output(["git", "-C", str(ROOT), "rev-parse", "HEAD"], text=True).strip()


def _read_lines(path: Path) -> list[str]:
    return path.read_text(encoding="utf-8").splitlines()


def run_cases() -> list[dict[str, Any]]:
    inputs, f, expected = _build_batch()
    out = jax.jit(gbm_columns)(
        inputs["u"], inputs["v"], inputs["t"], inputs["qv"], inputs["qc"],
        inputs["p"], inputs["pii"], inputs["dz"], inputs["tke"],
        psfc=f["psfc"], znt=f["znt"], ust=f["ust"], hfx=f["hfx"], qfx=f["qfx"],
        tsk=f["tsk"], gz1oz0=f["gz1oz0"], wspd=f["wspd"], br=f["br"],
        psim=f["psim"], psih=f["psih"], xland=f["xland"], dt=60.0,
    )
    out_np = {key: np.asarray(value) for key, value in out.items()}
    cases = []
    for i, case in enumerate(CASES):
        data = expected[i]
        s = data["scalars"]
        fields = {}
        for oracle_name, out_key in FIELDS.items():
            abs_tol = TKE_ABS_TOL if oracle_name == "TKE_PBL" else TEND_ABS_TOL
            rel_tol = TKE_REL_TOL if oracle_name == "TKE_PBL" else TEND_REL_TOL
            fields[oracle_name] = _metric(out_np[out_key][i], _col(data, oracle_name), abs_tol=abs_tol, rel_tol=rel_tol)
        diagnostics = {
            "PBL": _metric(out_np["pblh"][i], s["PBL"], abs_tol=PBL_ABS_TOL, rel_tol=PBL_REL_TOL),
            "KPBL": _metric(out_np["kpbl"][i], s["KPBL"], abs_tol=0.5, rel_tol=0.0),
            "UST": _metric(out_np["ust"][i], s["UST"], abs_tol=1.0e-10, rel_tol=1.0e-10),
        }
        case_report = {
            "case": case,
            "regime": s["REGIME"],
            "fields": fields,
            "diagnostics": diagnostics,
        }
        case_report["pass"] = bool(all(m["pass"] for m in fields.values()) and all(m["pass"] for m in diagnostics.values()))
        cases.append(case_report)
    return cases


def build_report() -> dict[str, Any]:
    cases = run_cases()
    overall = all(case["pass"] for case in cases)
    worst = {}
    for name in tuple(FIELDS) + ("PBL", "KPBL", "UST"):
        source = "fields" if name in FIELDS else "diagnostics"
        metrics = [(case["case"], case[source][name]["max_abs"], case[source][name]["max_rel"]) for case in cases]
        cid, max_abs, max_rel = max(metrics, key=lambda item: item[1])
        worst[name] = {"case": cid, "max_abs": max_abs, "max_rel": max_rel}
    return {
        "schema": "gpuwrf.v018.gbm_pbl12_jax_parity.v1",
        "scheme": "GBM moist TKE PBL (bl_pbl_physics=12)",
        "verdict": "PASS" if overall else "FAIL",
        "overall_pass": bool(overall),
        "operational_kernel": "gpuwrf.physics.bl_gbm.gbm_columns",
        "oracle": {
            "type": "single-column Fortran driver linked against UNMODIFIED pristine WRF phys/module_bl_gbmpbl.F",
            "savepoints": str(SP.relative_to(ROOT)),
            "full_wrf_exe": False,
            "self_compare": False,
            "source_checksums_sha256": _read_lines(SP / "gbm_wrf_source_checksums.txt"),
            "build_manifest": _read_lines(SP / "gbm_build_manifest.txt"),
        },
        "jax_backend": jax.default_backend(),
        "jax_precision": "fp64",
        "git_head": _git_head(),
        "tolerances": {
            "tend_abs": TEND_ABS_TOL,
            "tend_rel": TEND_REL_TOL,
            "tke_abs": TKE_ABS_TOL,
            "tke_rel": TKE_REL_TOL,
            "pbl_abs": PBL_ABS_TOL,
            "pbl_rel": PBL_REL_TOL,
        },
        "worst": worst,
        "cases": cases,
    }


def main() -> None:
    report = build_report()
    REPORT.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    if not report["overall_pass"]:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
