#!/usr/bin/env python3
"""v0.17 GFS PBL (bl_pbl_physics=3) savepoint-parity oracle.

Gates the ``jax.jit``/``jax.vmap``-traceable GFS kernel
(``physics.bl_gfs.gfs_columns``) against fp64 WRF-source savepoints produced by a
standalone Fortran driver linked against the UNMODIFIED pristine WRF
``phys/module_bl_gfs.F`` (+ ``module_gfs_machine.F`` / ``module_gfs_physcons.F``;
the real WRF-source oracle, NOT a JAX self-compare). The savepoints + build
manifest + source SHA-256 live under ``proofs/v017/savepoints_fp64/gfs/``
(generated by ``proofs/v017/oracle/gfs/build_and_run.sh``).

Covers all 6 regimes (unstable/strong-unstable/stable/marine/neutral/low-ust).
The batched kernel is exercised through ``jax.jit`` over the full 6-case batch to
prove the operational path is genuinely jit/vmap-traceable.

Run (CPU, fp64; the GPU is owned by another lane):

    taskset -c 0-3 env JAX_PLATFORMS=cpu CUDA_VISIBLE_DEVICES= PYTHONPATH=src \\
        python proofs/v017/gfs_oracle.py

Writes ``proofs/v017/gfs_oracle.json``.
"""

from __future__ import annotations

import json
import os
import subprocess
from pathlib import Path

os.environ.setdefault("JAX_PLATFORM_NAME", "cpu")
os.environ.setdefault("JAX_PLATFORMS", "cpu")

import jax
import jax.numpy as jnp
import numpy as np

jax.config.update("jax_enable_x64", True)

from gpuwrf.physics.bl_gfs import gfs_columns


ROOT = Path(__file__).resolve().parents[2]
SP = ROOT / "proofs" / "v017" / "savepoints_fp64" / "gfs"
REPORT = Path(__file__).resolve().parent / "gfs_oracle.json"
CASES = (1, 2, 3, 4, 5, 6)

# PREDECLARED fp64 operational-parity tolerances (kind_phys-native).
TEND_ABS_TOL = 5.0e-12
TEND_REL_TOL = 1.0e-9
PBLH_ABS_TOL = 1.0e-6
PBLH_REL_TOL = 1.0e-9
REL_FLOOR = 1.0e-30

TEND_FIELDS = ("RUBLTEN", "RVBLTEN", "RTHBLTEN", "RQVBLTEN", "RQCBLTEN")
TEND_KEYS = {
    "RUBLTEN": "rublten", "RVBLTEN": "rvblten", "RTHBLTEN": "rthblten",
    "RQVBLTEN": "rqvblten", "RQCBLTEN": "rqcblten",
}


def _load(case: int) -> dict:
    with (SP / f"gfs_case_{case}.json").open(encoding="utf-8") as fh:
        return json.load(fh)


def _col(d: dict, n: str) -> np.ndarray:
    return np.asarray(d["columns"][n], dtype=np.float64)


def _metric(actual, expected, *, abs_tol: float, rel_tol: float) -> dict:
    a = np.asarray(actual, dtype=np.float64).ravel()
    b = np.asarray(expected, dtype=np.float64).ravel()
    abs_err = np.abs(a - b)
    max_abs = float(np.max(abs_err))
    scale = max(float(np.max(np.abs(b))), REL_FLOOR)
    max_rel = max_abs / scale
    argmax = int(np.argmax(abs_err))
    return {
        "jax": float(a[argmax]),
        "oracle": float(b[argmax]),
        "max_abs": max_abs,
        "max_rel": float(max_rel),
        "scale": scale,
        "abs_tolerance": abs_tol,
        "rel_tolerance": rel_tol,
        "pass": bool(max_abs <= abs_tol or max_rel <= rel_tol),
    }


def _build_batch():
    keys = ("U", "V", "T", "QV", "P", "PI", "DZ", "Z")
    prof = {k: [] for k in keys}
    sc = {k: [] for k in ("PSFC", "UST", "HFX", "QFX", "TSK",
                          "GZ1OZ0", "WSPD", "BR", "PSIM", "PSIH")}
    expect = []
    for c in CASES:
        d = _load(c)
        s = d["scalars"]
        for k in keys:
            prof[k].append(_col(d, k))
        for k in sc:
            sc[k].append(s[k])
        expect.append(d)
    A = lambda L: jnp.asarray(np.stack(L), jnp.float64)
    qc_zero = jnp.zeros_like(A(prof["U"]))
    inputs = dict(
        u=A(prof["U"]), v=A(prof["V"]), t=A(prof["T"]), qv=A(prof["QV"]),
        qc=qc_zero, p=A(prof["P"]), pii=A(prof["PI"]), dz=A(prof["DZ"]), z=A(prof["Z"]),
    )
    scal = {k.lower(): jnp.asarray(np.asarray(v), jnp.float64) for k, v in sc.items()}
    return inputs, scal, expect


def _run_cases() -> list[dict]:
    inputs, scal, expect = _build_batch()
    fn = jax.jit(gfs_columns)
    out = fn(inputs["u"], inputs["v"], inputs["t"], inputs["qv"], inputs["qc"],
             inputs["p"], inputs["pii"], inputs["dz"], inputs["z"],
             psfc=scal["psfc"], ust=scal["ust"], hfx=scal["hfx"],
             qfx=scal["qfx"], tsk=scal["tsk"], gz1oz0=scal["gz1oz0"], wspd=scal["wspd"],
             psim=scal["psim"], psih=scal["psih"], br=scal["br"], dt=60.0)
    out = {k: np.asarray(v) for k, v in out.items()}
    cases = []
    for i, c in enumerate(CASES):
        d = expect[i]
        s = d["scalars"]
        fields = {
            name: _metric(out[TEND_KEYS[name]][i], _col(d, name),
                          abs_tol=TEND_ABS_TOL, rel_tol=TEND_REL_TOL)
            for name in TEND_FIELDS
        }
        scalars = {
            "PBL": _metric(out["pblh"][i], s["PBL"], abs_tol=PBLH_ABS_TOL, rel_tol=PBLH_REL_TOL),
            "KPBL": _metric(out["kpbl"][i], s["KPBL"], abs_tol=0.5, rel_tol=0.0),
        }
        case = {"case": c, "regime": s["REGIME"], "fields": fields, "scalars": scalars}
        case["pass"] = bool(
            all(m["pass"] for m in fields.values())
            and all(m["pass"] for m in scalars.values())
        )
        cases.append(case)
    return cases


def _read_lines(path: Path) -> list[str]:
    return path.read_text(encoding="utf-8").splitlines()


def _git_head() -> str:
    return subprocess.check_output(["git", "-C", str(ROOT), "rev-parse", "HEAD"], text=True).strip()


def build_report() -> dict:
    cases = _run_cases()
    overall = all(c["pass"] for c in cases)
    return {
        "schema": "gpuwrf.v017.gfs_savepoint_parity.v1",
        "scheme": "GFS PBL (bl_pbl_physics=3)",
        "verdict": "PASS" if overall else "FAIL",
        "overall_pass": bool(overall),
        "operational_kernel": "gpuwrf.physics.bl_gfs.gfs_columns (jit/vmap-traceable)",
        "exercised_through": "jax.jit over the full 6-case batch (genuine jit/vmap path)",
        "oracle": {
            "type": "single-column Fortran driver linked against UNMODIFIED pristine WRF "
                    "phys/module_bl_gfs.F (BL_GFS -> MONINP -> TRIDI2/TRIDIN/TRIDIT)",
            "savepoints": str(SP.relative_to(ROOT)),
            "wrf_sources": [
                "/home/enric/src/wrf_pristine/WRF/phys/module_bl_gfs.F",
                "/home/enric/src/wrf_pristine/WRF/phys/module_gfs_machine.F",
                "/home/enric/src/wrf_pristine/WRF/phys/module_gfs_physcons.F",
            ],
            "full_wrf_exe": False,
            "self_compare": False,
            "source_checksums_sha256": _read_lines(SP / "gfs_wrf_source_checksums.txt"),
            "build_manifest": _read_lines(SP / "gfs_build_manifest.txt"),
        },
        "jax_precision": "fp64",
        "jax_platform": jax.default_backend(),
        "git_head": _git_head(),
        "predeclared_tolerances": {
            "tendencies": {"abs": TEND_ABS_TOL, "rel": TEND_REL_TOL},
            "pblh_m": {"abs": PBLH_ABS_TOL, "rel": PBLH_REL_TOL},
            "relative_floor": REL_FLOOR,
        },
        "regimes_covered": [c["regime"] for c in cases],
        "cases": cases,
    }


def main() -> int:
    report = build_report()
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    with REPORT.open("w", encoding="utf-8") as fh:
        json.dump(report, fh, indent=2, sort_keys=True)
        fh.write("\n")
    print(f"verdict={report['verdict']} -> {REPORT}")
    worst = max(max(m["max_abs"] for m in c["fields"].values()) for c in report["cases"])
    print(f"worst |jax-oracle| tendency={worst:.3e}")
    for c in report["cases"]:
        wf = max(c["fields"].items(), key=lambda kv: kv[1]["max_abs"])
        print(f"  case {c['case']} {c['regime']:18s} pass={c['pass']} "
              f"PBL jax={c['scalars']['PBL']['jax']:.3f} oracle={c['scalars']['PBL']['oracle']:.3f} "
              f"worst={wf[0]} abs={wf[1]['max_abs']:.3e} rel={wf[1]['max_rel']:.3e}")
    return 0 if report["overall_pass"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
