"""MANAGER-OWNED (S5) — native real-init driver: wire the four lanes.

This is the ONLY production file the manager edits to integrate S1/S2/S3. The
lanes deliver against the frozen entry signatures in their own modules; the
driver calls them in dependency order and packs the result into the runtime
objects (State / BaseState / DycoreMetrics / BoundaryState).

Lane call order (the real dependency graph; see V0.4.0-S0-PLAN.md section 6):
  vcoord  = vertical_coord.compute_vertical_coord(config)          # S1, leaf
  surface = surface_init.compute_surface_init(config, metem)       # S2, leaf
  base    = base_state.compute_base_state(config, vcoord, surface.hgt)  # S1
  soil    = soil_init.compute_soil_init(config, metem, surface)    # S2
  seed    = vinterp.vertical_interpolate(config, vcoord, metem)    # S1
  dyn     = hydrostatic.balance(config, vcoord, base, seed)        # S1
  lbc     = lateral_bc.generate_lateral_bc(config, forcing_seq)    # S3 (d01 only)
  -> RealInitProduct(...)  -> pack into State/BaseState/DycoreMetrics/BoundaryState.

Until the lanes land, the driver stays a thin orchestrator that surfaces each
lane's NotImplementedError; the manager fills the final ``pack_*`` adapters
(which DO touch the manager-owned shared-core State contract — that is why the
pack lives here, not in any lane).

FREEZE: the lanes do NOT edit this file. The manager may.
"""

from __future__ import annotations

from collections.abc import Sequence

from gpuwrf.init.metgrid_schema import MetEmArtifact
from gpuwrf.init.real_init import base_state, hydrostatic, lateral_bc
from gpuwrf.init.real_init import soil_init, surface_init, vertical_coord, vinterp
from gpuwrf.init.real_init.types import RealInitConfig, RealInitProduct


def build_real_init(
    config: RealInitConfig,
    metem: MetEmArtifact,
    *,
    forcing_sequence: Sequence[MetEmArtifact] | None = None,
    domain: str = "d01",
) -> RealInitProduct:
    """Orchestrates the four lanes into a :class:`RealInitProduct`.

    ``metem`` is the init-time metgrid-equivalent artifact (drives wrfinput).
    ``forcing_sequence`` (when given, parent domain) drives the wrfbdy LBC; pass
    ``None`` for the single-time wrfinput-only path.
    """

    vcoord = vertical_coord.compute_vertical_coord(config)
    surface = surface_init.compute_surface_init(config, metem)
    base = base_state.compute_base_state(config, vcoord, surface.hgt)
    soil = soil_init.compute_soil_init(config, metem, surface)
    seed = vinterp.vertical_interpolate(config, vcoord, metem)
    dynamics = hydrostatic.balance(config, vcoord, base, seed)
    lbc = (
        lateral_bc.generate_lateral_bc(config, forcing_sequence)
        if forcing_sequence is not None
        else None
    )
    return RealInitProduct(
        domain=domain,
        init_time=metem.valid_time,
        config=config,
        vcoord=vcoord,
        base=base,
        dynamics=dynamics,
        surface=surface,
        soil=soil,
        lateral_bc=lbc,
        provenance={"interface_version": "0.4.0-S0-frozen-2026-06-02"},
    )
