"""The NVTX/cache evidence object must match the filesystem, not my recollection.

Manager review of `55df8bfe` found three factual errors in the hand-assembled
version of `nvtx_compile_evidence.json`, each contradicted by authoritative
filesystem evidence:

1. it tested the **deprecated** `jax_cache.DEFAULT_CACHE_DIR`
   (`<DATA_ROOT>/gpuwrf_jax_cache`) and concluded from that directory's absence
   that the warm-cache explanation was falsified. The canonical resolver in
   `compile_cache` points at `$HOME/.cache/gpuwrf/jit/<version-tag>`, which
   existed since Jul 23 and was written to during Stage 2;
2. it reported "2020 small-module entries / zero autotune files". It is 454
   top-level executable-cache files **plus** 1566 `.textproto` records inside
   `xla_gpu_per_fusion_autotune_cache_dir/` — the earlier search looked for files
   *named* `xla_gpu_per_fu*` when that is a **directory**;
3. it called 107,412 summary rows "ranges"; the instance total is 157,080.

The object is now generated by `build_nvtx_compile_evidence.py`, and these tests
hold it against the live filesystem so it cannot drift back.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[2]
if str(REPO / "scripts" / "v025") not in sys.path:
    sys.path.insert(0, str(REPO / "scripts" / "v025"))

EVIDENCE = REPO / "proofs/v025/m0/nvtx_compile_evidence.json"
pytestmark = pytest.mark.skipif(not EVIDENCE.exists(), reason="evidence object not built")


def _obj() -> dict:
    return json.loads(EVIDENCE.read_text())


# --------------------------------------------------------------------------- #
# 1. the canonical resolver                                                    #
# --------------------------------------------------------------------------- #
def test_the_canonical_resolver_is_used_not_the_deprecated_alias():
    node = _obj()["cache_provenance"]["canonical_resolver"]
    assert node["resolver"].endswith("compile_cache._default_cache_dir")
    assert "/.cache/gpuwrf/jit/" in node["path"], (
        "the object is not pointing at the canonical cache location"
    )
    assert "<DATA_ROOT>/gpuwrf_jax_cache" not in node["path"]


def test_the_deprecated_alias_is_recorded_as_such():
    """The wrong path must stay visible with a note, not be quietly dropped."""
    node = _obj()["cache_provenance"]["canonical_resolver"].get("deprecated_alias")
    assert node, "the deprecated alias that caused the error is not recorded"
    assert "jax_cache" in node["symbol"]
    assert "says nothing" in node["note"]


def test_the_backend_tag_aliasing_trap_is_documented():
    """A CPU generator resolves a different tag than the GPU process it describes."""
    node = _obj()["cache_provenance"]["canonical_resolver"]
    local = node.get("resolved_locally_as")
    assert local, "the local-vs-target tag difference is not recorded"
    assert local["version_tag"] != node["version_tag"]
    assert "cuda_sm120" in node["version_tag"]


def test_the_effective_stage2_cache_exists_and_predates_stage2():
    cache = _obj()["cache_provenance"]["stage2_effective_cache"]
    assert cache["exists"] is True
    assert cache["top_level_breakdown"]["cached_executables"] > 0


def test_the_falsification_is_explicitly_withdrawn():
    node = _obj()["the_346s_vs_4.382s_question"]
    assert "WITHDRAWN" in node["retracted_falsification"]
    assert node["status"] == "UNRESOLVED"
    assert node["MUST_NOT_BE_EQUATED"] is True


# --------------------------------------------------------------------------- #
# 2. directory-aware counts                                                    #
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("which", ["stage1_dedicated_cache", "stage2_effective_cache"])
def test_counts_are_directory_aware(which):
    """Top-level executable entries and nested autotune records are separate."""
    cache = _obj()["cache_provenance"][which]
    if not cache.get("exists"):
        pytest.skip(f"{which} not on disk")
    assert "top_level_files" in cache
    assert "autotune_records" in cache
    assert cache["total_files"] >= (
        cache["top_level_files"] + cache["autotune_records"]
    )


def test_stage1_matches_the_independently_verified_split():
    """454 top-level + 1566 autotune textproto — not '2020 small-module entries'."""
    cache = _obj()["cache_provenance"]["stage1_dedicated_cache"]
    if not cache.get("exists"):
        pytest.skip("stage 1 cache not on disk")
    assert cache["top_level_breakdown"]["cached_executables"] == 454
    assert cache["autotune_records"] == 1566
    assert cache["autotune_are_textproto"] == 1566
    assert cache["total_files"] == 2020


def test_only_the_top_level_big_module_count_is_claimed_zero():
    """Nothing may be claimed about the hashed autotune records."""
    node = _obj()["the_346s_vs_4.382s_question"]["only_proven_zero"]
    assert "TOP-LEVEL" in node
    assert "autotune" in node.lower()
    for which in ("stage1_dedicated_cache", "stage2_effective_cache"):
        cache = _obj()["cache_provenance"][which]
        if cache.get("exists"):
            assert cache["top_level_entries_for_big_module"] == 0


def test_autotune_records_are_not_attributed_to_a_module():
    for which in ("stage1_dedicated_cache", "stage2_effective_cache"):
        cache = _obj()["cache_provenance"][which]
        if cache.get("exists"):
            assert "NOT ATTRIBUTED" in cache["autotune_attribution"]


# --------------------------------------------------------------------------- #
# 3. rows vs instances                                                         #
# --------------------------------------------------------------------------- #
def test_rows_and_instances_are_both_named_and_different():
    nvtx = _obj()["nvtx"]
    assert nvtx["summary_rows"] == 107412
    assert nvtx["instance_total"] == 157080
    assert nvtx["summary_rows"] != nvtx["instance_total"]
    assert "different quantities" in nvtx["note"]


# --------------------------------------------------------------------------- #
# 4. partial scope, and no internal contradiction                              #
# --------------------------------------------------------------------------- #
def test_the_big_module_structure_is_described_as_partial():
    node = _obj()["big_module_scope"]
    assert node["structure_observed"] == "PARTIAL FRONT-END ONLY"
    assert node["codegen_rows"] == 0
    assert "NOT" in node["explanation"]


def test_autotune_presence_is_separated_from_time_dominance():
    """The earlier object claimed a 'volume signal' AND 'bearing: NONE' at once."""
    node = _obj()["bearing_on_pre_registered_H1"]
    assert node["autotune_presence"].startswith("EVIDENCED")
    assert node["autotune_time_dominance"] == "NOT MEASURED"
    assert "presence is not dominance" in node["verdict"]


def test_the_reduction_claim_does_not_overstate():
    text = _obj()["what_this_capture_reduces"]
    assert "PARTIAL" in text
    assert "does NOT establish autotune time dominance" in text


# --------------------------------------------------------------------------- #
# reproducibility                                                              #
# --------------------------------------------------------------------------- #
def test_the_object_is_generated_not_hand_written():
    node = _obj()["reproduce"]
    assert node["generator"].endswith("build_nvtx_compile_evidence.py")
    assert len(node["generator_sha256"]) == 64
    assert len(node["raw_nsys_rep_sha256"]) == 64
    assert len(node["raw_nvtx_csv_sha256"]) == 64
    assert "no number in this object is hand-written" in node["note"]


def test_the_generator_still_exists_and_hashes_as_recorded():
    import hashlib

    generator = REPO / "scripts/v025/build_nvtx_compile_evidence.py"
    assert generator.is_file()
    digest = hashlib.sha256(generator.read_bytes()).hexdigest()
    assert digest == _obj()["reproduce"]["generator_sha256"], (
        "the generator changed without the proof object being regenerated"
    )


# --------------------------------------------------------------------------- #
# b959 cache-proof hardening (manager follow-up)                               #
# --------------------------------------------------------------------------- #
def test_cached_executables_are_counted_separately_from_atime_sidecars():
    """987 top-level files is 493 executables, not 987 executables."""
    obj = _obj()
    stage2 = obj["cache_provenance"]["stage2_effective_cache"]
    breakdown = stage2["top_level_breakdown"]
    assert stage2["top_level_files"] == 987
    assert breakdown["cached_executables"] == 493
    assert breakdown["atime_sidecars"] == 493
    assert breakdown["lockfiles"] == 1
    assert (breakdown["cached_executables"] + breakdown["atime_sidecars"]
            + breakdown["lockfiles"] + len(breakdown["other"])) == stage2["top_level_files"]


def test_the_inflated_executable_count_is_retracted_in_place():
    correction = (_obj()["cache_provenance"]["stage2_effective_cache"]
                  ["top_level_breakdown"]["correction"])
    assert "executable cache files" in correction
    assert "roughly half" in correction


def test_each_cache_directory_carries_an_immutable_content_addressed_manifest():
    for key in ("stage2_effective_cache", "stage1_dedicated_cache"):
        manifest = _obj()["cache_provenance"][key]["cache_manifest"]
        assert manifest["content_addressed"] is True
        assert len(manifest["manifest_sha256"]) == 64
        assert manifest["entries"] == len(manifest["records"])
        assert all(len(row["sha256"]) == 64 for row in manifest["records"])


def test_the_manifest_digest_is_reproducible_from_its_own_records():
    """A manifest whose digest cannot be recomputed is not evidence."""
    import hashlib
    manifest = _obj()["cache_provenance"]["stage2_effective_cache"]["cache_manifest"]
    joined = "\n".join(f"{row['sha256']}  {row['name']}" for row in manifest["records"])
    assert hashlib.sha256(joined.encode()).hexdigest() == manifest["manifest_sha256"]


def test_temporal_coincidence_is_not_reported_as_causation():
    window = _obj()["cache_provenance"]["stage2_files_modified_in_window"]
    assert "NOT_CAUSAL" in window
    assert "temporal coincidence" in window["NOT_CAUSAL"]
    assert "writes" not in window.get("label", "")


def test_the_modified_set_is_broken_down_because_half_of_it_is_reads():
    """454 of the 920 are -atime sidecars, which JAX touches on cache READS."""
    window = _obj()["cache_provenance"]["stage2_files_modified_in_window"]
    assert window["breakdown"]["atime"] > 0
    assert window["breakdown"]["atime"] + window["breakdown"]["cache"] > 0.9 * window["count"]


def test_no_key_in_the_object_calls_these_writes():
    import json as _json
    text = _json.dumps(_obj())
    assert "writes_in_window" not in text
